import { type FormEvent, useEffect, useMemo, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { AlertTriangle, Gauge, PlayCircle, Plus, RefreshCw } from "lucide-react";
import { apiFetch } from "../auth/authStore";
import { FaenaSelect } from "../faenas/FaenaSelect";
import { Dialog } from "../../shared/ui/Dialog";

type Status = "Vigente" | "ProximoAVencer" | "EnVentana" | "Vencido" | "OTGenerada" | "Ejecutado" | "Reprogramado";
type Asset = { codigo: string; nombre: string; faenaCodigo?: string | null };
type Plan = { codigo: string; nombre: string; activoCodigo?: string | null; activoNombre?: string | null; faenaCodigo?: string | null; familiaEquipo?: string | null; marca?: string | null; modelo?: string | null; tipoFrecuencia: string; frecuenciaHoras?: number | null; frecuenciaKm?: number | null; frecuenciaDias?: number | null; toleranciaHoras: number; toleranciaKm: number; toleranciaDias: number; checklistCodigo?: string | null; repuestosSugeridos?: string | null; hhEstimadas: number; proximaFecha?: string | null; proximaHora?: number | null; proximoKm?: number | null; estado: Status; activo: boolean };
type Due = { planCodigo: string; nombre: string; activoCodigo: string; activoNombre?: string | null; faenaCodigo: string; estado: Status; numeroOT?: string | null; mensaje: string };
type Reading = { id: string; activoCodigo: string; activoNombre?: string | null; faenaCodigo?: string | null; fechaLecturaUtc: string; valor: number; unidad: string; esCorreccion: boolean; esAnomala: boolean; mensajeValidacion?: string | null };
type Calendar = { planCodigo: string; nombre: string; activoCodigo: string; activoNombre?: string | null; faenaCodigo: string; fecha: string; estado: Status; numeroOT?: string | null };
type History = { historyId: string; planCodigo: string; activoCodigo: string; estadoAnterior: Status; estadoNuevo: Status; fechaUtc: string; usuarioId: string; motivo: string; numeroOT?: string | null };
type Dashboard = { plans: Plan[]; dueItems: Due[]; calendar: Calendar[]; history: History[] };
type View = "overview" | "detail" | "calendar" | "readings";
const status: Record<Status, string> = { Vigente: "Vigente", ProximoAVencer: "Proximo", EnVentana: "En ventana", Vencido: "Vencido", OTGenerada: "OT generada", Ejecutado: "Ejecutado", Reprogramado: "Reprogramado" };
const newPlan = () => ({ codigo: "", nombre: "", activoCodigo: "", familiaEquipo: "", marca: "", modelo: "", frecuenciaHoras: "", frecuenciaKm: "", frecuenciaDias: "", toleranciaHoras: "0", toleranciaKm: "0", toleranciaDias: "0", checklistCodigo: "", repuestosSugeridos: "", hhEstimadas: "2", reason: "Configuracion preventivo" });
const newReading = () => ({ activoCodigo: "", valor: "", fechaLectura: new Date().toISOString().slice(0, 16), evidencia: "", autorizarCorreccion: false, motivoCorreccion: "" });

export function PreventiveMaintenancePage({ view = "overview" }: { view?: View }) {
  const { planCode } = useParams(); const navigate = useNavigate();
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [assets, setAssets] = useState<Asset[]>([]); const [readings, setReadings] = useState<Reading[]>([]);
  const [filters, setFilters] = useState({ faenaCodigo: "", activoCodigo: "", search: "" }); const [dialog, setDialog] = useState<"plan" | "reading" | "engine" | "generate" | "reprogram" | null>(null);
  const [planForm, setPlanForm] = useState(newPlan); const [readingForm, setReadingForm] = useState(newReading); const [reprogram, setReprogram] = useState({ proximaFecha: "", proximaHora: "", proximoKm: "", reason: "" }); const [due, setDue] = useState<Due | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void load(); }, [filters.faenaCodigo, filters.activoCodigo]);
  const plan = useMemo(() => dashboard?.plans.find(item => item.codigo === planCode) ?? null, [dashboard, planCode]);
  const plans = useMemo(() => (dashboard?.plans ?? []).filter(item => match(filters.search, item.codigo, item.nombre, item.activoNombre, item.activoCodigo, item.familiaEquipo, item.marca, item.modelo)), [dashboard, filters.search]);
  async function load() { setLoading(true); setError(null); try { const query = new URLSearchParams(); if (filters.faenaCodigo) query.set("faenaCodigo", filters.faenaCodigo); if (filters.activoCodigo) query.set("activoCodigo", filters.activoCodigo); const [data, page] = await Promise.all([apiFetch<Dashboard>(`/api/preventive/dashboard?${query}`), apiFetch<{ items: Asset[] }>(filters.faenaCodigo ? `/api/assets?faenaCodigo=${encodeURIComponent(filters.faenaCodigo)}&page=1&pageSize=100` : "/api/assets?page=1&pageSize=100")]); const scoped = filters.activoCodigo ? page.items.filter(item => item.codigo === filters.activoCodigo) : page.items; const groups = await Promise.all(scoped.map(async asset => (await apiFetch<Omit<Reading, "activoCodigo" | "activoNombre" | "faenaCodigo">[]>(`/api/assets/${encodeURIComponent(asset.codigo)}/readings`)).map(row => ({ ...row, activoCodigo: asset.codigo, activoNombre: asset.nombre, faenaCodigo: asset.faenaCodigo })))); setDashboard(data); setAssets(page.items); setReadings(groups.flat().sort((a,b) => b.fechaLecturaUtc.localeCompare(a.fechaLecturaUtc))); } catch (cause) { setError(cause instanceof Error ? cause.message : "No fue posible cargar preventivos."); } finally { setLoading(false); } }
  async function save(action: () => Promise<void>) { setSaving(true); setError(null); setMessage(null); try { await action(); await load(); setDialog(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "No fue posible guardar."); } finally { setSaving(false); } }
  async function createPlan(event: FormEvent) { event.preventDefault(); await save(async () => { const created = await apiFetch<Plan>("/api/preventive/plans", { method: "POST", body: JSON.stringify({ ...planForm, activoCodigo: nil(planForm.activoCodigo), familiaEquipo: nil(planForm.familiaEquipo), marca: nil(planForm.marca), modelo: nil(planForm.modelo), frecuenciaHoras: num(planForm.frecuenciaHoras), frecuenciaKm: num(planForm.frecuenciaKm), frecuenciaDias: num(planForm.frecuenciaDias), toleranciaHoras: Number(planForm.toleranciaHoras), toleranciaKm: Number(planForm.toleranciaKm), toleranciaDias: Number(planForm.toleranciaDias), checklistCodigo: nil(planForm.checklistCodigo), repuestosSugeridos: nil(planForm.repuestosSugeridos), hhEstimadas: Number(planForm.hhEstimadas), activo: true }) }); setPlanForm(newPlan()); setMessage("Plan preventivo guardado."); navigate(`/preventivos/planes/${encodeURIComponent(created.codigo)}`); }); }
  async function createReading(event: FormEvent) { event.preventDefault(); await save(async () => { const result = await apiFetch<{ esAnomala: boolean; mensajeValidacion?: string | null }>(`/api/assets/${encodeURIComponent(readingForm.activoCodigo)}/readings`, { method: "POST", body: JSON.stringify({ valor: Number(readingForm.valor), fechaLecturaUtc: new Date(readingForm.fechaLectura).toISOString(), origen: "MANUAL", evidenciaReferencia: nil(readingForm.evidencia), autorizarCorreccion: readingForm.autorizarCorreccion, motivoCorreccion: nil(readingForm.motivoCorreccion) }) }); setReadingForm(newReading()); setMessage(result.esAnomala ? result.mensajeValidacion ?? "Lectura guardada con alerta." : "Lectura guardada."); }); }
  async function engine() { await save(async () => { const result = await apiFetch<{ evaluated: number; generatedWorkOrders: number; alertsGenerated: number; warnings: string[] }>("/api/preventive/run", { method: "POST" }); setMessage(`Motor ejecutado: ${result.evaluated} evaluados, ${result.generatedWorkOrders} OT y ${result.alertsGenerated} alertas. ${result.warnings.join(" ")}`); }); }
  async function generate() { if (!due) return; await save(async () => { const result = await apiFetch<{ numeroOT: string; warnings: string[] }>(`/api/preventive/plans/${encodeURIComponent(due.planCodigo)}/generate-ot`, { method: "POST", body: JSON.stringify({ activoCodigo: due.activoCodigo, reason: "Generacion manual desde preventivos" }) }); setMessage(`OT ${result.numeroOT} generada. ${result.warnings.join(" ")}`); }); }
  async function reprogramPlan(event: FormEvent) { event.preventDefault(); if (!plan) return; await save(async () => { await apiFetch(`/api/preventive/plans/${encodeURIComponent(plan.codigo)}/reprogram`, { method: "POST", body: JSON.stringify({ proximaFecha: reprogram.proximaFecha ? new Date(reprogram.proximaFecha).toISOString() : null, proximaHora: num(reprogram.proximaHora), proximoKm: num(reprogram.proximoKm), reason: reprogram.reason }) }); setMessage("Preventivo reprogramado."); }); }
  const openReading = () => { setReadingForm(form => ({ ...form, activoCodigo: form.activoCodigo || filters.activoCodigo || plan?.activoCodigo || "" })); setDialog("reading"); };
  const counters = { plans: dashboard?.plans.length ?? 0, window: dashboard?.dueItems.filter(item => item.estado === "EnVentana").length ?? 0, overdue: dashboard?.dueItems.filter(item => item.estado === "Vencido").length ?? 0, generated: dashboard?.dueItems.filter(item => item.estado === "OTGenerada").length ?? 0 };
  return <section className="stack"><header className="page-header"><div><p className="eyebrow">Mantenimiento</p><h1>{view === "detail" ? plan ? `${plan.codigo} - ${plan.nombre}` : "Plan no encontrado" : view === "calendar" ? "Calendario preventivo" : view === "readings" ? "Lecturas" : "Preventivos"}</h1><p>Planes, vencimientos, lecturas y ordenes preventivas.</p></div><div className="toolbar"><button className="secondary-button" type="button" onClick={() => void load()}><RefreshCw size={18}/>Actualizar</button>{view === "overview" ? <><button className="secondary-button" type="button" onClick={openReading}><Gauge size={18}/>Registrar lectura</button><button className="primary-button" type="button" onClick={() => setDialog("plan")}><Plus size={18}/>Nuevo plan</button></> : view === "detail" ? <button className="secondary-button" type="button" onClick={() => navigate("/preventivos")}>Volver a planes</button> : <button className="secondary-button" type="button" onClick={openReading}>Registrar lectura</button>}</div></header>{message ? <div className="success-banner" role="status">{message}</div> : null}{error ? <div className="error-banner" role="alert">{error}</div> : null}
    {view !== "detail" ? <><section className="kpi-grid xl:grid-cols-4"><Metric label="Planes" value={counters.plans}/><Metric label="En ventana" value={counters.window}/><Metric label="Vencidos" value={counters.overdue} danger/><Metric label="OT generadas" value={counters.generated}/></section><section className="panel"><div className="grid gap-3 md:grid-cols-3"><FaenaSelect value={filters.faenaCodigo} onChange={faenaCodigo => setFilters({ ...filters, faenaCodigo, activoCodigo: "" })}/><label>Activo<select value={filters.activoCodigo} onChange={event => setFilters({ ...filters, activoCodigo: event.target.value })}><option value="">Todos</option>{assets.map(asset => <option key={asset.codigo} value={asset.codigo}>{asset.nombre} - {asset.codigo}</option>)}</select></label>{view === "overview" ? <label>Buscar<input aria-label="Buscar planes" value={filters.search} onChange={event => setFilters({ ...filters, search: event.target.value })}/></label> : null}</div></section></> : null}
    {view === "overview" ? <><div className="toolbar"><Link className="secondary-button" to="/preventivos/calendario">Calendario</Link><Link className="secondary-button" to="/preventivos/lecturas">Lecturas</Link><button className="secondary-button" type="button" onClick={() => setDialog("engine")}><PlayCircle size={18}/>Ejecutar evaluacion</button></div><Plans rows={plans} loading={loading}/></> : null}
    {view === "calendar" ? <CalendarTable rows={dashboard?.calendar ?? []} loading={loading}/> : null}{view === "readings" ? <Readings rows={readings} loading={loading}/> : null}
    {view === "detail" ? !loading && !plan ? <section className="panel"><h2>Registro no encontrado</h2></section> : plan ? <PlanDetail plan={plan} due={dashboard?.dueItems.filter(item => item.planCodigo === plan.codigo) ?? []} calendar={dashboard?.calendar.filter(item => item.planCodigo === plan.codigo) ?? []} history={dashboard?.history.filter(item => item.planCodigo === plan.codigo) ?? []} generate={item => { setDue(item); setDialog("generate"); }} reprogram={() => setDialog("reprogram")} reading={openReading}/> : null : null}
    <Dialog open={dialog === "plan"} title="Nuevo plan preventivo" busy={saving} onClose={() => setDialog(null)} className="max-w-5xl"><PlanForm form={planForm} assets={assets} setForm={setPlanForm} submit={createPlan} saving={saving}/></Dialog><Dialog open={dialog === "reading"} title="Registrar lectura" busy={saving} onClose={() => setDialog(null)}><ReadingForm form={readingForm} assets={assets} setForm={setReadingForm} submit={createReading} saving={saving}/></Dialog><Dialog open={dialog === "engine"} title="Ejecutar evaluacion preventiva" busy={saving} onClose={() => setDialog(null)} footer={<div className="toolbar"><button className="secondary-button" type="button" onClick={() => setDialog(null)} disabled={saving}>Cancelar</button><button className="primary-button" type="button" onClick={() => void engine()} disabled={saving}>Ejecutar motor</button></div>}><p>Se ejecutara el motor preventivo y se mostraran sus conteos y advertencias.</p></Dialog><Dialog open={dialog === "generate"} title="Generar OT preventiva" busy={saving} onClose={() => setDialog(null)} footer={<div className="toolbar"><button className="secondary-button" type="button" onClick={() => setDialog(null)} disabled={saving}>Cancelar</button><button className="primary-button" type="button" onClick={() => void generate()} disabled={saving}>Generar OT</button></div>}><p>{due ? `Se generara una OT para ${due.nombre}.` : ""}</p></Dialog><Dialog open={dialog === "reprogram"} title="Reprogramar preventivo" busy={saving} onClose={() => setDialog(null)}><form className="stack" onSubmit={reprogramPlan}><div className="form-grid"><label>Proxima fecha<input type="date" value={reprogram.proximaFecha} onChange={event => setReprogram({ ...reprogram, proximaFecha: event.target.value })}/></label><label>Proxima hora<input type="number" min="0" value={reprogram.proximaHora} onChange={event => setReprogram({ ...reprogram, proximaHora: event.target.value })}/></label><label>Proximo km<input type="number" min="0" value={reprogram.proximoKm} onChange={event => setReprogram({ ...reprogram, proximoKm: event.target.value })}/></label><label>Motivo<input required value={reprogram.reason} onChange={event => setReprogram({ ...reprogram, reason: event.target.value })}/></label></div><button className="primary-button" disabled={saving}>Reprogramar</button></form></Dialog></section>;
}
function Plans({ rows, loading }: { rows: Plan[]; loading: boolean }) { const navigate = useNavigate(); return <section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Estado</th><th>Codigo y nombre</th><th>Alcance</th><th>Faena</th><th>Frecuencia</th><th>Proximo vencimiento</th><th>HH</th></tr></thead><tbody>{loading ? <tr><td colSpan={7}>Cargando planes...</td></tr> : rows.length === 0 ? <tr><td colSpan={7}>No hay planes para los filtros seleccionados.</td></tr> : rows.map(item => <tr key={item.codigo} className="cursor-pointer hover:bg-teal-50 focus-within:bg-teal-50 dark:hover:bg-teal-950/30" tabIndex={0} aria-label={`Abrir plan ${item.codigo}`} onClick={() => navigate(`/preventivos/planes/${encodeURIComponent(item.codigo)}`)} onKeyDown={event => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); navigate(`/preventivos/planes/${encodeURIComponent(item.codigo)}`); } }}><td><Badge value={item.estado}/></td><td><strong>{item.codigo}</strong><small>{item.nombre}</small></td><td>{item.activoNombre ?? item.activoCodigo ?? ([item.familiaEquipo,item.marca,item.modelo].filter(Boolean).join(" / ") || "Familia")}</td><td>{item.faenaCodigo ?? "-"}</td><td>{frequency(item)}</td><td>{date(item.proximaFecha)}</td><td>{item.hhEstimadas}</td></tr>)}</tbody></table></div></section>; }
function PlanDetail({ plan, due, calendar, history, generate, reprogram, reading }: { plan: Plan; due: Due[]; calendar: Calendar[]; history: History[]; generate: (item: Due) => void; reprogram: () => void; reading: () => void }) { const [tab,setTab]=useState("summary"); return <><nav className="flex gap-2 overflow-x-auto border-b border-slate-200 pb-2 dark:border-slate-800" aria-label="Secciones del plan">{[["summary","Resumen"],["due","Vencimientos"],["calendar","Calendario"],["history","Historial"]].map(([id,label])=><button className={tab===id?"primary-button":"secondary-button"} key={id} type="button" onClick={()=>setTab(id)}>{label}</button>)}</nav><section className="grid gap-4 xl:grid-cols-[1fr_280px]"><section className="panel stack">{tab==="summary"?<div className="detail-grid"><Info label="Alcance" value={plan.activoNombre ?? plan.activoCodigo ?? [plan.familiaEquipo,plan.marca,plan.modelo].filter(Boolean).join(" / ")}/><Info label="Faena" value={plan.faenaCodigo}/><Info label="Frecuencia" value={frequency(plan)}/><Info label="Proximo vencimiento" value={date(plan.proximaFecha)}/><Info label="HH estimadas" value={String(plan.hhEstimadas)}/><Info label="Checklist" value={plan.checklistCodigo}/><Info label="Repuestos sugeridos" value={plan.repuestosSugeridos}/></div>:null}{tab==="due"?<DueRows rows={due} generate={generate}/>:null}{tab==="calendar"?<CalendarTable rows={calendar} loading={false}/>:null}{tab==="history"?<HistoryRows rows={history}/>:null}</section><aside className="panel stack"><h2>Acciones</h2><button className="primary-button" type="button" disabled={!due.length} onClick={()=>due[0]&&generate(due[0])}>Generar OT</button><button className="secondary-button" type="button" onClick={reprogram}>Reprogramar</button>{plan.activoCodigo?<button className="secondary-button" type="button" onClick={reading}>Registrar lectura</button>:null}</aside></section></>; }
function CalendarTable({ rows,loading }: { rows: Calendar[]; loading: boolean }) { return <section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Fecha</th><th>Estado</th><th>Plan</th><th>Activo</th><th>Faena</th><th>OT</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Cargando calendario...</td></tr>:rows.length===0?<tr><td colSpan={6}>No hay vencimientos.</td></tr>:rows.map(item=><tr key={`${item.planCodigo}-${item.activoCodigo}-${item.fecha}`}><td>{date(item.fecha)}</td><td><Badge value={item.estado}/></td><td>{item.nombre}</td><td>{item.activoNombre??item.activoCodigo}</td><td>{item.faenaCodigo}</td><td>{item.numeroOT?<Link to={`/ot/${encodeURIComponent(item.numeroOT)}`}>{item.numeroOT}</Link>:"-"}</td></tr>)}</tbody></table></div></section>; }
function Readings({ rows,loading }: { rows: Reading[]; loading: boolean }) { return <section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="data-table"><thead><tr><th>Fecha</th><th>Activo</th><th>Valor</th><th>Unidad</th><th>Correccion</th><th>Anomalia</th><th>Validacion</th></tr></thead><tbody>{loading?<tr><td colSpan={7}>Cargando lecturas...</td></tr>:rows.length===0?<tr><td colSpan={7}>No hay lecturas disponibles.</td></tr>:rows.map(item=><tr key={item.id}><td>{date(item.fechaLecturaUtc)}</td><td>{item.activoNombre??item.activoCodigo}</td><td>{item.valor}</td><td>{item.unidad}</td><td>{item.esCorreccion?"Si":"No"}</td><td>{item.esAnomala?"Si":"No"}</td><td>{item.mensajeValidacion??"-"}</td></tr>)}</tbody></table></div></section>; }
function DueRows({ rows,generate }: { rows: Due[]; generate:(item:Due)=>void }) { return <table className="data-table"><tbody>{rows.length===0?<tr><td>Sin vencimientos.</td></tr>:rows.map(item=><tr key={item.activoCodigo}><td><Badge value={item.estado}/></td><td>{item.activoNombre??item.activoCodigo}</td><td>{item.mensaje}</td><td>{item.numeroOT?<Link to={`/ot/${encodeURIComponent(item.numeroOT)}`}>{item.numeroOT}</Link>:<button className="secondary-button" type="button" onClick={()=>generate(item)}>Generar OT</button>}</td></tr>)}</tbody></table>; }
function HistoryRows({ rows }: { rows: History[] }) { return <table className="data-table"><tbody>{rows.length===0?<tr><td>Sin historial.</td></tr>:rows.map(item=><tr key={item.historyId}><td>{date(item.fechaUtc)}</td><td>{item.activoCodigo}</td><td>{status[item.estadoAnterior]} a {status[item.estadoNuevo]}</td><td>{item.motivo}</td><td>{item.numeroOT?<Link to={`/ot/${encodeURIComponent(item.numeroOT)}`}>{item.numeroOT}</Link>:"-"}</td></tr>)}</tbody></table>; }
function PlanForm({form,assets,setForm,submit,saving}:{form:ReturnType<typeof newPlan>;assets:Asset[];setForm:(value:ReturnType<typeof newPlan>)=>void;submit:(event:FormEvent)=>void;saving:boolean}) { return <form className="stack" onSubmit={submit}><div className="form-grid"><label>Codigo<input required value={form.codigo} onChange={e=>setForm({...form,codigo:e.target.value})}/></label><label>Nombre<input required value={form.nombre} onChange={e=>setForm({...form,nombre:e.target.value})}/></label><label>Activo<select value={form.activoCodigo} onChange={e=>setForm({...form,activoCodigo:e.target.value})}><option value="">Por familia</option>{assets.map(item=><option key={item.codigo} value={item.codigo}>{item.nombre}</option>)}</select></label>{(["familiaEquipo","marca","modelo","frecuenciaHoras","toleranciaHoras","frecuenciaKm","toleranciaKm","frecuenciaDias","toleranciaDias","checklistCodigo","repuestosSugeridos","hhEstimadas","reason"] as const).map(key=><label key={key}>{key==="reason"?"Motivo":key}<input required={key==="reason"} type={key.includes("frecuencia")||key.includes("tolerancia")||key==="hhEstimadas"?"number":"text"} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><button className="primary-button" disabled={saving}>Guardar plan</button></form>; }
function ReadingForm({form,assets,setForm,submit,saving}:{form:ReturnType<typeof newReading>;assets:Asset[];setForm:(value:ReturnType<typeof newReading>)=>void;submit:(event:FormEvent)=>void;saving:boolean}) { return <form className="stack" onSubmit={submit}><div className="form-grid"><label>Activo<select required value={form.activoCodigo} onChange={e=>setForm({...form,activoCodigo:e.target.value})}><option value="">Selecciona activo</option>{assets.map(item=><option key={item.codigo} value={item.codigo}>{item.nombre}</option>)}</select></label><label>Valor<input required type="number" min="0" value={form.valor} onChange={e=>setForm({...form,valor:e.target.value})}/></label><label>Fecha<input required type="datetime-local" value={form.fechaLectura} onChange={e=>setForm({...form,fechaLectura:e.target.value})}/></label><label>Evidencia<input value={form.evidencia} onChange={e=>setForm({...form,evidencia:e.target.value})}/></label><label className="check-row"><input type="checkbox" checked={form.autorizarCorreccion} onChange={e=>setForm({...form,autorizarCorreccion:e.target.checked})}/>Autorizar correccion</label><label>Motivo<input disabled={!form.autorizarCorreccion} value={form.motivoCorreccion} onChange={e=>setForm({...form,motivoCorreccion:e.target.value})}/></label></div><button className="primary-button" disabled={saving}>Guardar lectura</button></form>; }
function Metric({label,value,danger}:{label:string;value:number;danger?:boolean}) { return <article className="metric-card"><AlertTriangle size={18} className={danger?"text-red-600":"text-teal-600"}/><span>{label}</span><strong>{value}</strong></article>; } function Badge({value}:{value:string}) { return <span className={`status-pill ${value==="Vencido"?"danger":value==="Vigente"||value==="Ejecutado"?"success":""}`}>{status[value as Status]??value}</span>; } function Info({label,value}:{label:string;value?:string|null}) { return <div className="info-item"><span>{label}</span><strong>{value||"-"}</strong></div>; } function nil(value:string){return value.trim()||null;} function num(value:string){return value.trim()?Number(value):null;} function date(value?:string|null){return value?new Date(value).toLocaleDateString():"-";} function frequency(plan:Plan){return [[plan.frecuenciaHoras,"h"],[plan.frecuenciaKm,"km"],[plan.frecuenciaDias,"dias"]].filter(([value])=>value!=null).map(([value,unit])=>`${value} ${unit}`).join(" / ")||plan.tipoFrecuencia;} function match(search:string,...values:Array<string|null|undefined>){const value=search.trim().toLocaleLowerCase();return !value||values.some(item=>item?.toLocaleLowerCase().includes(value));}
