using System.Text.Json;
using MaintenanceCMMS.Application.Auditing;
using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.Inventory;
using MaintenanceCMMS.Domain.Common;
using MaintenanceCMMS.Domain.Enums;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities;
using Microsoft.EntityFrameworkCore;

namespace MaintenanceCMMS.Infrastructure.Inventory;

public sealed class InventoryService : IInventoryService
{
    private readonly CmmsDbContext _db;
    private readonly IAuditService _audit;
    private readonly IAuthorizationPolicyService _authorization;
    public InventoryService(CmmsDbContext db, IAuditService audit, IAuthorizationPolicyService authorization) { _db = db; _audit = audit; _authorization = authorization; }

    public async Task<InventoryDashboardResponse> GetDashboardAsync(UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var parts = await ListSparePartsAsync(new(), u, ct); var stock = await ListStockAsync(new(), u, ct); var wh = await ListWarehousesAsync(new(), u, ct);
        var alerts = stock.Where(x => x.BajoMinimo || x.CriticoSinStock).Select(x => new StockAlertResponse($"{x.BodegaCodigo}-{x.RepuestoCodigo}", x.CriticoSinStock ? "Critical" : "Warning", x.RepuestoCodigo, x.RepuestoDescripcion, x.BodegaCodigo, x.CriticoSinStock ? "Repuesto critico sin stock." : "Stock bajo minimo.")).ToArray();
        return new(parts.Count, parts.Count(x => x.Critico), parts.Count(x => x.EsNoCodificado), parts.Count(x => x.BajoMinimo), parts.Count(x => x.CriticoSinStock), wh.Count, stock.Sum(x => x.StockFisico), stock.Sum(x => x.StockDisponible), alerts);
    }

    public async Task<IReadOnlyCollection<WarehouseResponse>> ListWarehousesAsync(WarehouseQuery q, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var rows = await _db.Set<WarehouseEntity>().Include(x => x.Faena).Include(x => x.Type).Include(x => x.Locations).AsNoTracking().ToArrayAsync(ct);
        return rows.Select(ToWarehouse).Where(x => q.IncludeInactive || x.Activa).Where(x => !q.Tipo.HasValue || x.Tipo == q.Tipo).Where(x => Empty(q.FaenaCodigo) || Same(x.FaenaCodigo,q.FaenaCodigo)).OrderBy(x => x.Codigo).ToArray();
    }

    public async Task<WarehouseResponse> CreateWarehouseAsync(CreateWarehouseRequest r, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); Required(r.Codigo,nameof(r.Codigo)); Required(r.Nombre,nameof(r.Nombre)); var faena = await _db.Faenas.SingleOrDefaultAsync(x => x.Code.ToUpper() == Code(r.FaenaCodigo),ct) ?? throw new DomainException("La faena no existe.");
        if (await _db.Set<WarehouseEntity>().AnyAsync(x => x.Code.ToUpper() == Code(r.Codigo),ct)) throw new DomainException($"Ya existe una bodega con codigo '{r.Codigo}'.");
        var type = await CatalogAsync("WarehouseType", r.Tipo.ToString(),ct); var e = new WarehouseEntity { Code=Code(r.Codigo)!, Name=r.Nombre.Trim(), FaenaId=faena.Id, TypeId=type.Id, Location=Trim(r.Ubicacion), ResponsibleUserId=Trim(r.Responsable), IsActive=r.Activa, AllowsNegativeStock=r.PermiteStockNegativo, CreatedByUserId=u.UserId };
        foreach(var location in r.UbicacionesInternas ?? []) if(!string.IsNullOrWhiteSpace(location)) e.Locations.Add(new WarehouseLocationEntity { Code=Code(location)!, Name=location.Trim() });
        _db.Add(e); await _db.SaveChangesAsync(ct); await Audit(u,"warehouse.created","Warehouse",e.Code,null,e,faena.Code,null,ct); return ToWarehouse(e);
    }

    public async Task<IReadOnlyCollection<SparePartSummary>> ListSparePartsAsync(SparePartQuery q, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var parts=await _db.Set<SparePartEntity>().Include(x=>x.Unit).Include(x=>x.Category).AsNoTracking().ToArrayAsync(ct); var stock=await _db.Set<WarehouseStockEntity>().AsNoTracking().ToArrayAsync(ct);
        return parts.Select(p=>ToSummary(p,stock.Where(s=>s.SparePartId==p.Id))).Where(x=>q.IncludeObsolete||x.Estado!=SparePartStatus.Obsoleto).Where(x=>!q.Estado.HasValue||x.Estado==q.Estado).Where(x=>!q.CriticalOnly||x.Critico).Where(x=>!q.LowStockOnly||x.BajoMinimo||x.CriticoSinStock).Where(x=>Empty(q.Familia)||Same(x.FamiliaEquipo,q.Familia)).Where(x=>Empty(q.Search)||x.Codigo.Contains(q.Search!,StringComparison.OrdinalIgnoreCase)||x.Descripcion.Contains(q.Search!,StringComparison.OrdinalIgnoreCase)).OrderBy(x=>x.Codigo).ToArray();
    }

    public async Task<SparePartDetail?> GetSparePartAsync(string code, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var p=await PartAsync(code,ct,false); if(p is null) return null; var s=(await ListSparePartsAsync(new(),u,ct)).Single(x=>Same(x.Codigo,code)); var stock=await ListStockAsync(new(RepuestoCodigo:code),u,ct); var moves=await ListMovementsAsync(new(RepuestoCodigo:code,Take:500),u,ct); return new(s,stock,moves);
    }

    public async Task<SparePartDetail> CreateSparePartAsync(CreateSparePartRequest r, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); ValidatePart(r.Descripcion,r.UnidadMedida,r.StockMinimo,r.StockMaximo,r.PuntoReposicion,r.LeadTimeEsperadoDias); if(!Empty(r.CodigoSap)&&await _db.Set<SparePartEntity>().AnyAsync(x=>x.SapCode!.ToUpper()==Code(r.CodigoSap),ct)) throw new DomainException("Ya existe un repuesto con el codigo SAP indicado.");
        var unit=await CatalogAsync("Unit",r.UnidadMedida,ct); var category=Empty(r.FamiliaEquipo)?null:await CatalogAsync("SparePartCategory",r.FamiliaEquipo!,ct); var n=await NextAsync("spare_part_number_seq","REP",ct); var e=PartEntity(n,r,unit.Id,category?.Id,u.UserId); _db.Add(e); await _db.SaveChangesAsync(ct); await Audit(u,"spare_part.created","SparePart",e.Code,null,e,null,null,ct); return (await GetSparePartAsync(e.Code,u,ct))!;
    }

    public async Task<SparePartDetail?> UpdateSparePartAsync(string code, UpdateSparePartRequest r, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); ValidatePart(r.Descripcion,r.UnidadMedida,r.StockMinimo,r.StockMaximo,r.PuntoReposicion,r.LeadTimeEsperadoDias); var e=await PartAsync(code,ct,true); if(e is null)return null; if(!Empty(r.CodigoSap)&&await _db.Set<SparePartEntity>().AnyAsync(x=>x.Id!=e.Id&&x.SapCode!.ToUpper()==Code(r.CodigoSap),ct))throw new DomainException("Ya existe un repuesto con el codigo SAP indicado."); var before=JsonSerializer.Serialize(e); var unit=await CatalogAsync("Unit",r.UnidadMedida,ct); var cat=Empty(r.FamiliaEquipo)?null:await CatalogAsync("SparePartCategory",r.FamiliaEquipo!,ct); ApplyPart(e,r,unit.Id,cat?.Id,u.UserId); await _db.SaveChangesAsync(ct); await Audit(u,"spare_part.updated","SparePart",e.Code,before,e,null,r.Reason,ct); return await GetSparePartAsync(code,u,ct);
    }

    public async Task<IReadOnlyCollection<StockItemResponse>> ListStockAsync(StockQuery q, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var rows=await _db.Set<WarehouseStockEntity>().Include(x=>x.Warehouse).ThenInclude(x=>x.Faena).Include(x=>x.SparePart).ThenInclude(x=>x.Unit).AsNoTracking().ToArrayAsync(ct); return rows.Select(ToStock).Where(x=>Empty(q.BodegaCodigo)||Same(x.BodegaCodigo,q.BodegaCodigo)).Where(x=>Empty(q.RepuestoCodigo)||Same(x.RepuestoCodigo,q.RepuestoCodigo)).Where(x=>Empty(q.FaenaCodigo)||Same(x.FaenaCodigo,q.FaenaCodigo)).Where(x=>!q.LowStockOnly||x.BajoMinimo||x.CriticoSinStock).Where(x=>!q.CriticalOnly||x.RepuestoCritico).OrderBy(x=>x.BodegaCodigo).ThenBy(x=>x.RepuestoCodigo).ToArray();
    }

    public async Task<IReadOnlyCollection<StockMovementResponse>> ListMovementsAsync(StockMovementQuery q, UserAccessContext u, CancellationToken ct)
    {
        EnsureView(u); var rows=await _db.Set<StockMovementEntity>().Include(x=>x.MovementType).Include(x=>x.SparePart).Include(x=>x.SourceWarehouse).Include(x=>x.TargetWarehouse).AsNoTracking().ToArrayAsync(ct); return rows.Select(ToMovement).Where(x=>Empty(q.BodegaCodigo)||Same(x.BodegaCodigo,q.BodegaCodigo)||Same(x.BodegaOrigenCodigo,q.BodegaCodigo)||Same(x.BodegaDestinoCodigo,q.BodegaCodigo)).Where(x=>Empty(q.RepuestoCodigo)||Same(x.RepuestoCodigo,q.RepuestoCodigo)).Where(x=>!q.Type.HasValue||x.Type==q.Type).Where(x=>Empty(q.ReferenceType)||Same(x.ReferenceType,q.ReferenceType)).Where(x=>Empty(q.ReferenceId)||Same(x.ReferenceId,q.ReferenceId)).OrderByDescending(x=>x.FechaUtc).Take(Math.Clamp(q.Take,1,500)).ToArray();
    }

    public async Task<StockMovementResponse> RegisterMovementAsync(StockMovementRequest r, UserAccessContext u, CancellationToken ct)
    {
        EnsureAdjust(u); Positive(r.Quantity); Required(r.Reason,nameof(r.Reason)); await using var tx=await _db.Database.BeginTransactionAsync(ct); var movement=await ApplyMovement(r,u,null,null,null,ct); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); await Audit(u,"stock.movement","StockMovement",movement.MovementNumber,null,movement,null,r.Reason,ct); return await MovementResponse(movement.Id,ct);
    }

    public async Task<IReadOnlyCollection<StockReservationResponse>> ListReservationsAsync(UserAccessContext u,CancellationToken ct)
    { EnsureView(u); return (await _db.Set<StockReservationEntity>().Include(x=>x.SparePart).Include(x=>x.Warehouse).AsNoTracking().OrderByDescending(x=>x.CreatedAtUtc).ToArrayAsync(ct)).Select(ToReservation).ToArray(); }

    public async Task<StockReservationResponse> CreateReservationAsync(CreateStockReservationRequest r,UserAccessContext u,CancellationToken ct)
    {
        EnsureAdjust(u); Positive(r.Quantity); Required(r.WorkOrderId,nameof(r.WorkOrderId)); var part=await RequiredPart(r.RepuestoCodigo,ct); var wh=await RequiredWarehouse(r.BodegaCodigo,ct); EnsureActive(wh); await using var tx=await _db.Database.BeginTransactionAsync(ct); var stock=await StockForUpdate(part.Id,wh.Id,ct); if(stock.PhysicalQuantity-stock.ReservedQuantity<r.Quantity)throw new DomainException("Stock disponible insuficiente para reservar."); var n=await NextAsync("stock_reservation_number_seq","RES",ct); var wo=await _db.WorkOrders.SingleOrDefaultAsync(x=>x.WorkOrderNumber.ToUpper()==Code(r.WorkOrderId),ct); var reservation=new StockReservationEntity{ReservationNumber=n,SparePartId=part.Id,WarehouseId=wh.Id,RequestedQuantity=r.Quantity,ReservedQuantity=r.Quantity,WorkOrderId=wo?.Id,WorkOrderNumber=r.WorkOrderId.Trim(),RequestedBy=r.RequestedBy.Trim(),Reason=r.Reason.Trim(),CreatedByUserId=u.UserId}; stock.ReservedQuantity+=r.Quantity; stock.UpdatedAtUtc=DateTimeOffset.UtcNow; _db.Add(reservation); var movement=await AddMovement(StockMovementType.Reservation,part,wh,null,r.Quantity,stock.PhysicalQuantity,stock.PhysicalQuantity,stock.ReservedQuantity-r.Quantity,stock.ReservedQuantity,r.Reason,u,"ReservaOT",n,reservation,null,ct); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); await Audit(u,"stock.reservation_created","StockReservation",n,null,reservation,wh.Faena.Code,r.Reason,ct); return ToReservation(reservation);
    }

    public async Task<StockReservationResponse?> ReleaseReservationAsync(string id,ReleaseStockReservationRequest r,UserAccessContext u,CancellationToken ct)
    {
        EnsureAdjust(u); Positive(r.Quantity); var reservation=await _db.Set<StockReservationEntity>().Include(x=>x.SparePart).Include(x=>x.Warehouse).ThenInclude(x=>x.Faena).SingleOrDefaultAsync(x=>x.ReservationNumber.ToUpper()==Code(id),ct); if(reservation is null)return null; if(reservation.Status is "Entregada" or "Liberada" or "Cancelada")throw new DomainException("La reserva no admite nuevas liberaciones."); var pending=reservation.ReservedQuantity-reservation.DeliveredQuantity-reservation.ReleasedQuantity; if(r.Quantity>pending)throw new DomainException("La cantidad a liberar excede el saldo pendiente de la reserva."); await using var tx=await _db.Database.BeginTransactionAsync(ct); var stock=await StockForUpdate(reservation.SparePartId,reservation.WarehouseId,ct); var before=stock.ReservedQuantity; stock.ReservedQuantity-=r.Quantity; reservation.ReleasedQuantity+=r.Quantity; reservation.ReleasedAtUtc=DateTimeOffset.UtcNow; if(reservation.DeliveredQuantity+reservation.ReleasedQuantity>=reservation.ReservedQuantity)reservation.Status="Liberada"; await AddMovement(StockMovementType.ReservationRelease,reservation.SparePart,reservation.Warehouse,null,r.Quantity,stock.PhysicalQuantity,stock.PhysicalQuantity,before,stock.ReservedQuantity,r.Reason,u,"ReservaOT",reservation.ReservationNumber,reservation,null,ct); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); await Audit(u,"stock.reservation_released","StockReservation",id,null,reservation,reservation.Warehouse.Faena.Code,r.Reason,ct); return ToReservation(reservation);
    }

    public async Task<StockMovementResponse> DeliverMaterialAsync(DeliverMaterialRequest r,UserAccessContext u,CancellationToken ct)
    {
        EnsureAdjust(u); Positive(r.Quantity); Required(r.Reason,nameof(r.Reason)); if(Empty(r.WorkOrderId)&&Empty(r.AssetCode)&&Empty(r.FaenaCodigo)&&Empty(r.CostCenter))throw new DomainException("La entrega de material requiere OT, activo, faena o centro de costo."); await using var tx=await _db.Database.BeginTransactionAsync(ct); StockReservationEntity? reservation=null; if(!Empty(r.ReservationId)){ reservation=await _db.Set<StockReservationEntity>().Include(x=>x.SparePart).Include(x=>x.Warehouse).SingleOrDefaultAsync(x=>x.ReservationNumber.ToUpper()==Code(r.ReservationId),ct)??throw new DomainException("La reserva no existe."); var pending=reservation.ReservedQuantity-reservation.DeliveredQuantity-reservation.ReleasedQuantity; if(r.Quantity>pending)throw new DomainException("La entrega excede la reserva pendiente."); }
        var m=await ApplyMovement(new(StockMovementType.MaintenanceConsumption,r.RepuestoCodigo,r.Quantity,r.Reason,BodegaCodigo:r.BodegaCodigo,ReferenceType:"OT",ReferenceId:r.WorkOrderId),u,reservation,null,null,ct); if(reservation is not null){reservation.DeliveredQuantity+=r.Quantity; reservation.DeliveredAtUtc=DateTimeOffset.UtcNow; reservation.Status=reservation.DeliveredQuantity+reservation.ReleasedQuantity>=reservation.ReservedQuantity?"Entregada":"ParcialmenteEntregada";} await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return await MovementResponse(m.Id,ct);
    }

    public async Task<IReadOnlyCollection<StockTransferResponse>> ListTransfersAsync(UserAccessContext u,CancellationToken ct)
    { EnsureView(u); var x=await _db.Set<StockTransferEntity>().Include(t=>t.SparePart).Include(t=>t.SourceWarehouse).Include(t=>t.TransitWarehouse).Include(t=>t.TargetWarehouse).AsNoTracking().OrderByDescending(t=>t.RequestedAtUtc).ToArrayAsync(ct); var m=await ListMovementsAsync(new(ReferenceType:"Transferencia",Take:500),u,ct); return x.Select(t=>ToTransfer(t,m.Where(z=>Same(z.ReferenceId,t.TransferNumber)).ToArray())).ToArray(); }

    public async Task<StockTransferResponse> TransferStockAsync(TransferStockRequest r,UserAccessContext u,CancellationToken ct)
    {
        EnsureAdjust(u); Positive(r.Quantity); if(Same(r.SourceWarehouseCode,r.TargetWarehouseCode))throw new DomainException("La transferencia requiere bodegas origen y destino distintas."); var p=await RequiredPart(r.RepuestoCodigo,ct); var source=await RequiredWarehouse(r.SourceWarehouseCode,ct); var transit=await RequiredWarehouse(r.TransitWarehouseCode,ct); var target=await RequiredWarehouse(r.TargetWarehouseCode,ct); if(!Same(transit.Type.Code, WarehouseType.Transito.ToString()))throw new DomainException("La bodega de transito debe ser de tipo Transito."); EnsureActive(source);EnsureActive(transit);EnsureActive(target); var n=Empty(r.TransferId)?await NextAsync("stock_transfer_number_seq","TRF",ct):Code(r.TransferId)!; if(await _db.Set<StockTransferEntity>().AnyAsync(x=>x.TransferNumber==n,ct))throw new DomainException("Ya existe la transferencia indicada."); await using var tx=await _db.Database.BeginTransactionAsync(ct); var tr=new StockTransferEntity{TransferNumber=n,SourceWarehouseId=source.Id,TransitWarehouseId=transit.Id,TargetWarehouseId=target.Id,SparePartId=p.Id,Quantity=r.Quantity,Reason=r.Reason.Trim(),RequestedByUserId=u.UserId}; _db.Add(tr); await ApplyMovement(new(StockMovementType.InTransit,p.Code,r.Quantity,r.Reason,SourceWarehouseCode:source.Code,TargetWarehouseCode:transit.Code,ReferenceType:"Transferencia",ReferenceId:n),u,null,tr,null,ct); if (!await _db.Set<WarehouseStockEntity>().AnyAsync(x => x.SparePartId == p.Id && x.WarehouseId == transit.Id, ct)) _db.Add(new WarehouseStockEntity { SparePartId = p.Id, WarehouseId = transit.Id }); await _db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return ToTransfer(tr,await ListMovementsAsync(new(ReferenceType:"Transferencia",ReferenceId:n,Take:50),u,ct));
    }

    public async Task<StockTransferResponse?> ReceiveTransferAsync(string id,ReceiveTransferRequest r,UserAccessContext u,CancellationToken ct)
    {
        EnsureAdjust(u); var tr=await _db.Set<StockTransferEntity>().Include(x=>x.SparePart).Include(x=>x.SourceWarehouse).Include(x=>x.TransitWarehouse).Include(x=>x.TargetWarehouse).SingleOrDefaultAsync(x=>x.TransferNumber.ToUpper()==Code(id),ct); if(tr is null)return null; if(tr.Status!="EnTransito")throw new DomainException("La transferencia no esta pendiente de recepcion."); await using var tx=await _db.Database.BeginTransactionAsync(ct); await ApplyMovement(new(StockMovementType.TransferReception,tr.SparePart.Code,tr.Quantity,r.Reason,SourceWarehouseCode:tr.TransitWarehouse.Code,TargetWarehouseCode:tr.TargetWarehouse.Code,ReferenceType:"Transferencia",ReferenceId:tr.TransferNumber),u,null,tr,null,ct); tr.Status="Recibida";tr.ReceivedAtUtc=DateTimeOffset.UtcNow;tr.ReceivedByUserId=u.UserId;tr.ReceptionReason=r.Reason.Trim(); await _db.SaveChangesAsync(ct);await tx.CommitAsync(ct); return ToTransfer(tr,await ListMovementsAsync(new(ReferenceType:"Transferencia",ReferenceId:tr.TransferNumber,Take:50),u,ct));
    }

    public Task<StockMovementResponse> ReturnStockAsync(ReturnStockRequest r,UserAccessContext u,CancellationToken ct) => RegisterMovementAsync(new(r.Reusable?StockMovementType.ReturnFromWorkOrder:StockMovementType.MaterialWriteOff,r.RepuestoCodigo,r.Quantity,r.Reason,BodegaCodigo:r.BodegaCodigo,ReferenceType:"OT",ReferenceId:r.WorkOrderId??r.AssetCode),u,ct);
    public Task<StockMovementResponse> AdjustStockAsync(AdjustStockRequest r,UserAccessContext u,CancellationToken ct) => RegisterMovementAsync(new(r.Quantity>=0?StockMovementType.PositiveAdjustment:StockMovementType.NegativeAdjustment,r.RepuestoCodigo,Math.Abs(r.Quantity),r.Reason,BodegaCodigo:r.BodegaCodigo,AllowNegativeException:r.AllowNegativeException),u,ct);
    public Task<StockMovementResponse> WriteOffStockAsync(WriteOffStockRequest r,UserAccessContext u,CancellationToken ct) => RegisterMovementAsync(new(StockMovementType.MaterialWriteOff,r.RepuestoCodigo,r.Quantity,r.Reason,BodegaCodigo:r.BodegaCodigo,ReferenceType:r.ReferenceType,ReferenceId:r.ReferenceId,AllowNegativeException:r.AllowNegativeException),u,ct);

    private async Task<StockMovementEntity> ApplyMovement(StockMovementRequest r,UserAccessContext u,StockReservationEntity? reservation,StockTransferEntity? transfer,Guid? wo,CancellationToken ct)
    {
        var part=await RequiredPart(r.RepuestoCodigo,ct); var source=Empty(r.SourceWarehouseCode)?(Empty(r.BodegaCodigo)?null:await RequiredWarehouse(r.BodegaCodigo!,ct)):await RequiredWarehouse(r.SourceWarehouseCode!,ct); var target=Empty(r.TargetWarehouseCode)?null:await RequiredWarehouse(r.TargetWarehouseCode!,ct); if(source is not null)EnsureActive(source);if(target is not null)EnsureActive(target); var outgoing=r.Type is StockMovementType.MaintenanceConsumption or StockMovementType.TransferOut or StockMovementType.InTransit or StockMovementType.NegativeAdjustment or StockMovementType.MaterialWriteOff; var incoming=r.Type is StockMovementType.Reception or StockMovementType.TransferIn or StockMovementType.TransferReception or StockMovementType.ReturnFromWorkOrder or StockMovementType.PositiveAdjustment or StockMovementType.Adjustment or StockMovementType.CountCorrection;
        if(r.Type is StockMovementType.Reservation or StockMovementType.ReservationRelease) { if(source is null) throw new DomainException("El movimiento requiere bodega."); var reserved = await StockForUpdate(part.Id, source.Id, ct); var pb0=reserved.PhysicalQuantity; var rb0=reserved.ReservedQuantity; if(r.Type == StockMovementType.Reservation) { if(reserved.PhysicalQuantity-reserved.ReservedQuantity<r.Quantity) throw new DomainException("Stock disponible insuficiente."); reserved.ReservedQuantity += r.Quantity; } else { if(reserved.ReservedQuantity<r.Quantity) throw new DomainException("Stock reservado insuficiente."); reserved.ReservedQuantity -= r.Quantity; } return await AddMovement(r.Type,part,source,null,r.Quantity,pb0,pb0,rb0,reserved.ReservedQuantity,r.Reason,u,r.ReferenceType,r.ReferenceId,reservation,transfer,ct,wo); } if(!outgoing&&!incoming)throw new DomainException("Tipo de movimiento no soportado directamente."); if(outgoing&&source is null)throw new DomainException("El movimiento requiere bodega origen."); if(incoming&&target is null)target=source; if(incoming&&target is null)throw new DomainException("El movimiento requiere bodega destino.");
        WarehouseStockEntity? changed=null; decimal pb=0,pa=0,rb=0,ra=0; if(outgoing){changed=await StockForUpdate(part.Id,source!.Id,ct); pb=changed.PhysicalQuantity;rb=changed.ReservedQuantity;if(changed.PhysicalQuantity-r.Quantity<changed.ReservedQuantity&&!r.AllowNegativeException)throw new DomainException("Stock insuficiente para la salida solicitada.");changed.PhysicalQuantity-=r.Quantity;pa=changed.PhysicalQuantity;ra=changed.ReservedQuantity;} else {changed=await StockForUpdate(part.Id,target!.Id,ct,true);pb=changed.PhysicalQuantity;rb=changed.ReservedQuantity;changed.PhysicalQuantity+=r.Quantity;pa=changed.PhysicalQuantity;ra=changed.ReservedQuantity;}
        return await AddMovement(r.Type,part,source,target,r.Quantity,pb,pa,rb,ra,r.Reason,u,r.ReferenceType,r.ReferenceId,reservation,transfer,ct,wo);
    }
    private async Task<WarehouseStockEntity> StockForUpdate(Guid part,Guid wh,CancellationToken ct,bool create=false)
    { var s=await _db.Set<WarehouseStockEntity>().SingleOrDefaultAsync(x=>x.SparePartId==part&&x.WarehouseId==wh&&x.WarehouseLocationId==null,ct); if(s is null){if(!create){s=new WarehouseStockEntity{SparePartId=part,WarehouseId=wh};_db.Add(s);}else{s=new WarehouseStockEntity{SparePartId=part,WarehouseId=wh};_db.Add(s);}} return s; }
    private async Task<StockMovementEntity> AddMovement(StockMovementType type,SparePartEntity part,WarehouseEntity? source,WarehouseEntity? target,decimal quantity,decimal pb,decimal pa,decimal rb,decimal ra,string reason,UserAccessContext u,string? refType,string? refId,StockReservationEntity? res,StockTransferEntity? tr,CancellationToken ct,Guid? wo=null)
    { var cat=await CatalogAsync("MovementType",type.ToString(),ct);var m=new StockMovementEntity{MovementNumber=await NextAsync("stock_movement_number_seq","MOV",ct),MovementTypeId=cat.Id,SparePartId=part.Id,Quantity=quantity,SourceWarehouseId=source?.Id,TargetWarehouseId=target?.Id,Reservation=res,Transfer=tr,WorkOrderId=wo,ReferenceType=Trim(refType),ReferenceId=Trim(refId),Reason=reason.Trim(),UserId=u.UserId,PhysicalBefore=pb,PhysicalAfter=pa,ReservedBefore=rb,ReservedAfter=ra};_db.Add(m);return m; }
    private async Task<StockMovementResponse> MovementResponse(Guid id,CancellationToken ct){var e=await _db.Set<StockMovementEntity>().Include(x=>x.MovementType).Include(x=>x.SparePart).Include(x=>x.SourceWarehouse).Include(x=>x.TargetWarehouse).SingleAsync(x=>x.Id==id,ct);return ToMovement(e);}
    private async Task<SparePartEntity?> PartAsync(string code,CancellationToken ct,bool tracked){var q=_db.Set<SparePartEntity>().Include(x=>x.Unit).Include(x=>x.Category).Where(x=>x.Code.ToUpper()==Code(code));return tracked?await q.SingleOrDefaultAsync(ct):await q.AsNoTracking().SingleOrDefaultAsync(ct);}
    private async Task<SparePartEntity> RequiredPart(string c,CancellationToken ct)=>await PartAsync(c,ct,true)??throw new DomainException("El repuesto no existe.");
    private async Task<WarehouseEntity> RequiredWarehouse(string c,CancellationToken ct)=>await _db.Set<WarehouseEntity>().Include(x=>x.Faena).Include(x=>x.Type).SingleOrDefaultAsync(x=>x.Code.ToUpper()==Code(c),ct)??throw new DomainException("La bodega no existe.");
    private async Task<InventoryCatalogEntity> CatalogAsync(string cat,string code,CancellationToken ct) { var value = Code(code)!; var existing = await _db.Set<InventoryCatalogEntity>().SingleOrDefaultAsync(x => x.Category == cat && x.Code == value && x.IsActive, ct); if (existing is not null) return existing; var created = new InventoryCatalogEntity { Category = cat, Code = value, Name = value, IsActive = true }; _db.Add(created); return created; }
    private async Task<string> NextAsync(string seq,string prefix,CancellationToken ct){var n=await _db.Database.SqlQuery<long>($"SELECT nextval({seq}) AS \"Value\"").SingleAsync(ct);return $"{prefix}-{n:000000}";}
    private static WarehouseResponse ToWarehouse(WarehouseEntity x)=>new(x.Code,x.Name,x.Faena.Code,Parse(x.Type.Code,WarehouseType.Faena),x.Location,x.Locations.Where(l=>l.IsActive).Select(l=>l.Name).ToArray(),x.IsActive,x.ResponsibleUserId,x.AllowsNegativeStock);
    private static SparePartSummary ToSummary(SparePartEntity p,IEnumerable<WarehouseStockEntity> s){var a=s.ToArray();var ph=a.Sum(x=>x.PhysicalQuantity);var re=a.Sum(x=>x.ReservedQuantity);var av=ph-re;return new(p.Code,p.SapCode,p.SupplierCode,p.Description,p.TechnicalDescription,p.Unit.Code,p.Category?.Code,p.Manufacturer,p.ModelReference,p.IsCritical,p.MinimumStock,p.MaximumStock,p.ReorderPoint,p.LeadTimeDays,p.AverageUnitCost,Parse(p.Status,SparePartStatus.Activo),Empty(p.SapCode),p.PreferredSupplier,p.ReplacementCode,ph,re,av,ph<p.MinimumStock,p.IsCritical&&ph<=0);}
    private static StockItemResponse ToStock(WarehouseStockEntity s){var min=s.MinimumStockOverride??s.SparePart.MinimumStock;return new(s.Warehouse.Code,s.Warehouse.Name,s.Warehouse.Faena.Code,s.SparePart.Code,s.SparePart.Description,s.SparePart.Unit.Code,s.SparePart.IsCritical,s.PhysicalQuantity,s.ReservedQuantity,s.PhysicalQuantity-s.ReservedQuantity,min,s.SparePart.MaximumStock,s.SparePart.ReorderPoint,s.PhysicalQuantity<min,s.SparePart.IsCritical&&s.PhysicalQuantity<=0,s.UpdatedAtUtc??s.CreatedAtUtc);}
    private static StockMovementResponse ToMovement(StockMovementEntity x)=>new(x.MovementNumber,x.OccurredAtUtc,Parse(x.MovementType.Code,StockMovementType.Reception),x.SparePart.Code,x.SourceWarehouse?.Code??x.TargetWarehouse?.Code,x.SourceWarehouse?.Code,x.TargetWarehouse?.Code,x.Quantity,x.PhysicalBefore,x.PhysicalAfter,x.ReservedBefore,x.ReservedAfter,x.Reason,x.UserId,x.ReferenceType,x.ReferenceId,false);
    private static StockReservationResponse ToReservation(StockReservationEntity x)=>new(x.ReservationNumber,Parse(x.Status,StockReservationStatus.Activa),x.CreatedAtUtc,x.SparePart.Code,x.Warehouse.Code,x.ReservedQuantity,x.DeliveredQuantity,x.ReleasedQuantity,x.ReservedQuantity-x.DeliveredQuantity-x.ReleasedQuantity,x.WorkOrderNumber,x.RequestedBy,x.Reason,x.CreatedByUserId);
    private static StockTransferResponse ToTransfer(StockTransferEntity x,IReadOnlyCollection<StockMovementResponse> m)=>new(x.TransferNumber,Parse(x.Status,StockTransferStatus.EnTransito),x.RequestedAtUtc,x.ReceivedAtUtc,x.SparePart.Code,x.SourceWarehouse.Code,x.TransitWarehouse.Code,x.TargetWarehouse.Code,x.Quantity,x.Reason,x.RequestedByUserId,x.ReceivedByUserId,x.ReceptionReason,m);
    private static SparePartEntity PartEntity(string code,CreateSparePartRequest r,Guid unit,Guid? cat,string user)=>new(){Code=code,CreatedByUserId=user,Description=r.Descripcion.Trim(),TechnicalDescription=Trim(r.DescripcionTecnica)??r.Descripcion.Trim(),UnitId=unit,CategoryId=cat,SapCode=Trim(r.CodigoSap),SupplierCode=Trim(r.CodigoProveedor),Manufacturer=Trim(r.MarcaFabricante),ModelReference=Trim(r.ModeloReferencia),IsCritical=r.Critico,MinimumStock=r.StockMinimo??0,MaximumStock=r.StockMaximo??0,ReorderPoint=r.PuntoReposicion??0,LeadTimeDays=r.LeadTimeEsperadoDias??0,AverageUnitCost=r.CostoUnitarioPromedio,Status=r.Estado.ToString(),PreferredSupplier=Trim(r.ProveedorPreferente),ReplacementCode=Code(r.ReemplazoCodigo)};
    private static void ApplyPart(SparePartEntity e,UpdateSparePartRequest r,Guid unit,Guid? cat,string user){e.Description=r.Descripcion.Trim();e.TechnicalDescription=Trim(r.DescripcionTecnica)??r.Descripcion.Trim();e.UnitId=unit;e.CategoryId=cat;e.SapCode=Trim(r.CodigoSap);e.SupplierCode=Trim(r.CodigoProveedor);e.Manufacturer=Trim(r.MarcaFabricante);e.ModelReference=Trim(r.ModeloReferencia);e.IsCritical=r.Critico;e.MinimumStock=r.StockMinimo??0;e.MaximumStock=r.StockMaximo??0;e.ReorderPoint=r.PuntoReposicion??0;e.LeadTimeDays=r.LeadTimeEsperadoDias??0;e.AverageUnitCost=r.CostoUnitarioPromedio;e.Status=r.Estado.ToString();e.PreferredSupplier=Trim(r.ProveedorPreferente);e.ReplacementCode=Code(r.ReemplazoCodigo);e.UpdatedByUserId=user;e.UpdatedAtUtc=DateTimeOffset.UtcNow;}
    private async Task Audit(UserAccessContext u,string action,string entity,string id,object? before,object after,string? faena,string? reason,CancellationToken ct)=>await _audit.RecordAsync(new(u.UserId,action,AuditModules.Stock,entity,id,before?.ToString(),JsonSerializer.Serialize(after, new JsonSerializerOptions { ReferenceHandler = System.Text.Json.Serialization.ReferenceHandler.IgnoreCycles }),faena,AuditSeverity.Medium,reason),ct);
    private static void EnsureView(UserAccessContext u){if(u.Roles.Contains(AuthRoles.Admin,StringComparer.OrdinalIgnoreCase)||u.Permissions.Contains(AuthPermissions.ViewGlobalWarehouses,StringComparer.OrdinalIgnoreCase)||u.Permissions.Contains(AuthPermissions.AdjustStock,StringComparer.OrdinalIgnoreCase))return;throw new UnauthorizedAccessException("No tiene permisos para inventario.");}
    private static void EnsureAdjust(UserAccessContext u){if(u.Roles.Contains(AuthRoles.Admin,StringComparer.OrdinalIgnoreCase)||u.Permissions.Contains(AuthPermissions.AdjustStock,StringComparer.OrdinalIgnoreCase))return;throw new UnauthorizedAccessException("La accion requiere permiso de ajuste de stock.");}
    private static void EnsureActive(WarehouseEntity x){if(!x.IsActive)throw new DomainException("La bodega esta inactiva.");}
    private static void Positive(decimal n){if(n<=0)throw new DomainException("La cantidad debe ser mayor que cero.");}
    private static void Required(string? x,string n){if(Empty(x))throw new DomainException($"El campo {n} es obligatorio.");}
    private static void ValidatePart(string d,string unit,decimal? min,decimal? max,decimal? point,int? lead){Required(d,nameof(d));Required(unit,nameof(unit));if((min??0)<0||(max??0)<0||(point??0)<0||(lead??0)<0)throw new DomainException("Los valores de stock y lead time no pueden ser negativos.");}
    private static bool Empty(string? x)=>string.IsNullOrWhiteSpace(x); private static string? Trim(string? x)=>Empty(x)?null:x!.Trim(); private static string? Code(string? x)=>Empty(x)?null:x!.Trim().ToUpperInvariant(); private static bool Same(string? a,string? b)=>string.Equals(Trim(a),Trim(b),StringComparison.OrdinalIgnoreCase); private static T Parse<T>(string? x,T fallback)where T:struct=>Enum.TryParse<T>(x,true,out var value)?value:fallback;
}


