import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { RefreshCw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { DocumentStatusBadge } from "./components/DocumentStatusBadge";
import { documentApi } from "./components/documentApi";
import type { DocumentRecord } from "./components/documentFormTypes";

type Filters = { entityCode: string; type: string; status: string; history: boolean };
const empty: Filters = { entityCode: "", type: "", status: "", history: false };

function DocumentOwnerLink({ document, onAsset, onUnit, label }: { document: DocumentRecord; onAsset: () => void; onUnit: (code: string) => void; label?: string }) {
  const context = useQuery({ queryKey: ["operational-unit-document-context", document.entidadCodigo], queryFn: () => documentApi.unitContextForAsset(document.entidadCodigo), retry: false });
  if (context.data) return <div><button className="text-left font-medium text-teal-700 underline" type="button" onClick={() => onUnit(context.data!.unitCode)}>{label ?? context.data.unitCode}</button><small className="mt-1 block text-slate-500">Asociado a {document.entidadCodigo} ({context.data.technicalOwnerRole})</small></div>;
  return <button className="text-left font-medium text-teal-700 underline" type="button" onClick={onAsset}>{label ?? document.entidadCodigo}</button>;
}

export function DocumentsPage() {
  const navigate = useNavigate(); const [draft, setDraft] = useState<Filters>(empty); const [filters, setFilters] = useState<Filters>(empty);
  const query = useQuery({ queryKey: ["documents", filters], queryFn: () => { const parameters = new URLSearchParams({ entidadTipo: "Activo", includeHistorical: String(filters.history) }); if (filters.entityCode) parameters.set("entidadCodigo", filters.entityCode); if (filters.type) parameters.set("tipoDocumento", filters.type); if (filters.status) parameters.set("estado", filters.status); return documentApi.list(parameters); } });
  const goToAsset = (code: string) => navigate("/equipos/activos/" + encodeURIComponent(code) + "?tab=documentos");
  const goToUnit = (code: string) => navigate("/equipos/unidades/" + encodeURIComponent(code) + "?tab=documentos");
  const documents = query.data ?? [];
  return <section className="space-y-5"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Documentos</h1><p className="text-sm text-slate-500">Consulta global. Los documentos de componentes actualmente montados se gestionan desde la unidad operativa.</p></div><button className="secondary-button" type="button" onClick={() => void query.refetch()}><RefreshCw className="h-4 w-4" />Actualizar</button></header><form className="panel grid gap-3 md:grid-cols-4" onSubmit={event => { event.preventDefault(); setFilters({ ...draft }); }}><label className="text-sm font-medium">Activo<input className="input mt-1" value={draft.entityCode} onChange={event => setDraft(current => ({ ...current, entityCode: event.target.value }))} /></label><label className="text-sm font-medium">Tipo documental<input className="input mt-1" value={draft.type} onChange={event => setDraft(current => ({ ...current, type: event.target.value }))} /></label><label className="text-sm font-medium">Estado<select className="input mt-1" value={draft.status} onChange={event => setDraft(current => ({ ...current, status: event.target.value }))}><option value="">Todos</option>{["Vigente", "PorVencer", "Vencido", "PendienteCarga", "PendienteValidacion", "Rechazado", "Reemplazado", "Anulado"].map(status => <option key={status}>{status}</option>)}</select></label><label className="flex items-end gap-2 text-sm"><input checked={draft.history} type="checkbox" onChange={event => setDraft(current => ({ ...current, history: event.target.checked }))} />Incluir históricos</label><button className="primary-button md:col-span-4" type="submit">Aplicar filtros</button></form>{query.error ? <p className="error-banner">{query.error instanceof Error ? query.error.message : "No fue posible cargar documentos."}</p> : null}<div className="overflow-x-auto rounded-lg border border-slate-200 bg-white"><table className="min-w-full text-sm"><thead><tr><th>Entidad visible</th><th>Tipo</th><th>Estado</th><th>Vencimiento</th><th /></tr></thead><tbody>{query.isLoading ? <tr><td className="p-4" colSpan={5}>Cargando...</td></tr> : documents.length ? documents.map(document => <tr className="border-t" key={document.documentoId}><td className="p-3"><DocumentOwnerLink document={document} onAsset={() => goToAsset(document.entidadCodigo)} onUnit={goToUnit} /></td><td className="p-3">{document.tipoDocumento}</td><td className="p-3"><DocumentStatusBadge status={document.estado} /></td><td className="p-3">{document.fechaVencimiento ?? "NA"}</td><td className="p-3"><DocumentOwnerLink document={document} label="Gestionar" onAsset={() => goToAsset(document.entidadCodigo)} onUnit={code => goToUnit(code)} /></td></tr>) : <tr><td className="p-6 text-center text-slate-500" colSpan={5}>No hay documentos.</td></tr>}</tbody></table></div></section>;
}