using MaintenanceCMMS.Application.Auditing;
using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.Inventory;
using MaintenanceCMMS.Application.MaterialRequests;
using MaintenanceCMMS.Infrastructure.Auditing;
using MaintenanceCMMS.Infrastructure.Inventory;
using MaintenanceCMMS.Infrastructure.MaterialRequests;
using MaintenanceCMMS.Infrastructure.Security;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace MaintenanceCMMS.Tests;
public sealed class MaterialRequestServiceTests
{
 private static readonly UserAccessContext Admin=new("admin",[AuthRoles.Admin],[AuthPermissions.Administration,AuthPermissions.AdjustStock,AuthPermissions.ViewGlobalWarehouses],[]);
 [Fact] public async Task CodedRequest_ReservesDeliversAndPersists(){await using var f=await Fixture.CreateAsync();var wh=await f.Inventory.CreateWarehouseAsync(new("BOD-01","Bodega","FAE-1",WarehouseType.Faena),Admin,default);var p=await f.Inventory.CreateSparePartAsync(new("Filtro","UN",CodigoSap:"SAP-1"),Admin,default);await f.Inventory.RegisterMovementAsync(new(MaintenanceCMMS.Domain.Enums.StockMovementType.Reception,p.Summary.Codigo,10,"Ingreso",BodegaCodigo:wh.Codigo),Admin,default);var r=await f.Service.CreateAsync(new(MaterialRequestSource.Bodega,MaterialRequestType.RepuestoCodificado,"Filtro",2,"UN","Mantencion",RepuestoCodigo:p.Summary.Codigo,FaenaCodigo:"FAE-1"),Admin,default);await f.Service.ApproveMaintenanceAsync(r.NumeroSolicitud,new("Aprobado"),Admin,default);var reserved=await f.Service.ReviewWarehouseAsync(r.NumeroSolicitud,new("BOD-01","Reservar"),Admin,default);Assert.Equal(MaterialRequestStatus.Reservada,reserved!.Estado);var delivered=await f.Service.DeliverAsync(r.NumeroSolicitud,new("BOD-01","Entregar"),Admin,default);Assert.Equal(MaterialRequestStatus.Entregada,delivered!.Estado);await using var second=f.NewContext();Assert.True(await second.Set<MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities.MaterialRequestEntity>().AnyAsync(x=>x.RequestNumber==r.NumeroSolicitud));}
 [Fact] public async Task NonCodedRequest_GoesToSupplyAndCanConvert(){await using var f=await Fixture.CreateAsync();await f.Inventory.CreateWarehouseAsync(new("BOD-02","Bodega","FAE-1",WarehouseType.Faena),Admin,default);var r=await f.Service.CreateAsync(new(MaterialRequestSource.Bodega,MaterialRequestType.MaterialNoCodificado,"Sensor",1,"UN","Normalizar",FaenaCodigo:"FAE-1"),Admin,default);await f.Service.ApproveMaintenanceAsync(r.NumeroSolicitud,new("Ok"),Admin,default);var reviewed=await f.Service.ReviewWarehouseAsync(r.NumeroSolicitud,new("BOD-02","Sin catalogo"),Admin,default);Assert.Equal(MaterialRequestStatus.PendienteAbastecimiento,reviewed!.Estado);var converted=await f.Service.ConvertToSparePartAsync(r.NumeroSolicitud,new("Sensor","UN",CodigoSap:"SAP-S"),Admin,default);Assert.NotNull(converted!.RepuestoCodigo);}
 [Fact] public async Task InvalidTransitionsAndFaenaAccess_AreRejected(){await using var f=await Fixture.CreateAsync();var r=await f.Service.CreateAsync(new(MaterialRequestSource.Bodega,MaterialRequestType.MaterialNoCodificado,"Manguera",1,"UN","Prueba",FaenaCodigo:"FAE-1"),Admin,default);await Assert.ThrowsAsync<MaintenanceCMMS.Domain.Common.DomainException>(()=>f.Service.DeliverAsync(r.NumeroSolicitud,new("BOD-X","No"),Admin,default));var denied=new UserAccessContext("x",[AuthRoles.Technician],[],["FAE-2"]);await Assert.ThrowsAsync<UnauthorizedAccessException>(()=>f.Service.GetByIdAsync(r.NumeroSolicitud,denied,default));}
 private sealed class Fixture:IAsyncDisposable{private Fixture(PostgreSqlWorkTestFixture x){Db=x;Inventory=new InventoryService(x.DbContext,new PostgreSqlAuditService(x.DbContext,new AuditContextAccessor()),new AuthorizationPolicyService());Service=new MaterialRequestService(x.DbContext,Inventory,new PostgreSqlAuditService(x.DbContext,new AuditContextAccessor()));}public PostgreSqlWorkTestFixture Db{get;}public IInventoryService Inventory{get;}public IMaterialRequestService Service{get;}public static async Task<Fixture>CreateAsync()=>new(await PostgreSqlWorkTestFixture.CreateAsync());public Microsoft.EntityFrameworkCore.DbContext NewContext()=>Db.NewContext();public ValueTask DisposeAsync()=>Db.DisposeAsync();}
}
