using System.Text.Json;
using MaintenanceCMMS.Application.Auditing;
using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.Inventory;
using MaintenanceCMMS.Application.MaterialRequests;
using MaintenanceCMMS.Domain.Common;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities;
using Microsoft.EntityFrameworkCore;

namespace MaintenanceCMMS.Infrastructure.MaterialRequests;
public sealed class MaterialRequestService : IMaterialRequestService
{
 private readonly CmmsDbContext db; private readonly IInventoryService inventory; private readonly IAuditService audit;
 public MaterialRequestService(CmmsDbContext dbContext,IInventoryService inventoryService,IAuditService auditService){db=dbContext;inventory=inventoryService;audit=auditService;}
 public async Task<IReadOnlyCollection<MaterialRequestResponse>> ListAsync(MaterialRequestQuery q,UserAccessContext u,CancellationToken ct){View(u);var a=await Base().AsNoTracking().ToArrayAsync(ct);return a.Select(Map).Where(x=>q.IncludeClosed||x.Estado is not(MaterialRequestStatus.Cerrada or MaterialRequestStatus.Rechazada)).Where(x=>!q.Status.HasValue||x.Estado==q.Status).Where(x=>!q.Type.HasValue||x.Tipo==q.Type).Where(x=>!q.Source.HasValue||x.Origen==q.Source).Where(x=>E(q.FaenaCodigo)||Same(x.FaenaCodigo,q.FaenaCodigo)).Where(x=>E(q.Requester)||Same(x.Solicitante,q.Requester)).Where(x=>Access(u,x.FaenaCodigo)).OrderByDescending(x=>x.SolicitadoEnUtc).ToArray();}
 public async Task<MaterialRequestResponse?> GetByIdAsync(string id,UserAccessContext u,CancellationToken ct){View(u);var e=await Find(id,ct);if(e is null)return null;var r=Map(e);Faena(u,r.FaenaCodigo);return r;}
 public async Task<MaterialRequestResponse> CreateAsync(CreateMaterialRequestRequest r,UserAccessContext u,CancellationToken ct){Request(u);Validate(r);Faena(u,r.FaenaCodigo);var faena=await FaenaEntity(r.FaenaCodigo,ct);var ot=await Ot(r.OtNumero,ct);var asset=await Asset(r.ActivoCodigo,ct);if(ot?.FaenaId!=null&&faena?.Id!=ot.FaenaId)throw new DomainException("La OT no pertenece a la faena.");if(asset?.FaenaId!=null&&faena?.Id!=asset.FaenaId)throw new DomainException("El activo no pertenece a la faena.");var part=await Part(r.RepuestoCodigo,ct);if(r.Type==MaterialRequestType.RepuestoCodificado&&part is null)throw new DomainException("El repuesto no existe.");var e=new MaterialRequestEntity{RequestNumber=await Next(ct),Status=MaterialRequestStatus.PendienteAprobacionMantenimiento.ToString(),RequestType=r.Type.ToString(),Source=r.Source.ToString(),Faena=faena,WorkOrder=ot,Asset=asset,RequesterUserId=u.UserId,TechnicalDescription=r.DescripcionTecnica.Trim(),Unit=r.Unidad.Trim(),Reason=r.Motivo.Trim(),PhotoReference=N(r.FotoReferencia),TaskCode=N(r.TareaCodigo),StockDecision="Pendiente de aprobacion de mantenimiento"};e.Items.Add(new MaterialRequestItemEntity{SparePart=part,RequestedQuantity=r.Cantidad,Unit=r.Unidad.Trim()});db.Add(e);await db.SaveChangesAsync(ct);await Hist(e,"",e.Status,u,r.Motivo,ct);await Audit(u,"material_request.created",e,null,r.Motivo,ct);return Map(e);}
 public Task<MaterialRequestResponse?> ApproveMaintenanceAsync(string id,MaterialRequestReasonRequest r,UserAccessContext u,CancellationToken ct)=>Change(id,u,ct,"material_request.maintenance_approved",r.Reason,x=>{Maint(u);Status(x,MaterialRequestStatus.PendienteAprobacionMantenimiento);x.Status=MaterialRequestStatus.AprobadaPorMantenimiento.ToString();x.MaintenanceApproverUserId=u.UserId;x.MaintenanceApprovedAtUtc=DateTimeOffset.UtcNow;x.StockDecision="Aprobada por mantenimiento; pendiente revision bodega";});
 public Task<MaterialRequestResponse?> RejectAsync(string id,MaterialRequestReasonRequest r,UserAccessContext u,CancellationToken ct)=>Change(id,u,ct,"material_request.rejected",r.Reason,x=>{Reject(u);if(Parse(x.Status,MaterialRequestStatus.Solicitada) is MaterialRequestStatus.Cerrada or MaterialRequestStatus.Entregada or MaterialRequestStatus.RecibidaPorTecnico)throw new DomainException("La solicitud ya no admite rechazo.");x.Status=MaterialRequestStatus.Rechazada.ToString();x.RejectedByUserId=u.UserId;x.RejectedAtUtc=DateTimeOffset.UtcNow;x.RejectReason=r.Reason;});
 public async Task<MaterialRequestResponse?> ReviewWarehouseAsync(string id,WarehouseReviewMaterialRequestRequest r,UserAccessContext u,CancellationToken ct){WarehouseApprove(u);Need(r.BodegaCodigo,"BodegaCodigo");Need(r.Reason,"Reason");var e=await Find(id,ct);if(e is null)return null;Faena(u,e.Faena?.Code);Status(e,MaterialRequestStatus.AprobadaPorMantenimiento,MaterialRequestStatus.EnRevisionBodega);var w=await Warehouse(r.BodegaCodigo,ct)??throw new DomainException("La bodega no existe.");if(e.FaenaId.HasValue&&w.FaenaId!=e.FaenaId)throw new DomainException("La bodega no pertenece a la faena.");var item=e.Items.Single();var old=e.Status;e.Warehouse=w;e.WarehouseApproverUserId=u.UserId;e.WarehouseApprovedAtUtc=DateTimeOffset.UtcNow;if(Parse(e.RequestType,MaterialRequestType.RepuestoCodificado)==MaterialRequestType.MaterialNoCodificado){e.Status=MaterialRequestStatus.PendienteAbastecimiento.ToString();e.StockDecision="Material no codificado derivado a abastecimiento";}else{var stock=await inventory.ListStockAsync(new StockQuery(w.Code,item.SparePart!.Code),u,ct);var s=stock.FirstOrDefault(x=>x.StockDisponible>=item.RequestedQuantity);if(s is not null){var res=await inventory.CreateReservationAsync(new CreateStockReservationRequest(s.RepuestoCodigo,s.BodegaCodigo,item.RequestedQuantity,E(e.WorkOrder?.WorkOrderNumber)?$"SOL-{e.RequestNumber}":e.WorkOrder!.WorkOrderNumber,e.RequesterUserId,$"Solicitud {e.RequestNumber}: {r.Reason}"),u,ct);item.ReservationId=await db.Set<StockReservationEntity>().Where(x=>x.ReservationNumber==res.ReservaId).Select(x=>(Guid?)x.Id).SingleOrDefaultAsync(ct);item.ReservedQuantity=item.RequestedQuantity;e.Status=MaterialRequestStatus.Reservada.ToString();e.StockDecision="Reserva automatica generada";}else{e.Status=stock.Any(x=>x.StockDisponible>0)?MaterialRequestStatus.PendienteStock.ToString():MaterialRequestStatus.PendienteAbastecimiento.ToString();e.StockDecision=stock.Any(x=>x.StockDisponible>0)?"Stock insuficiente en bodega":"Sin stock disponible; derivado a abastecimiento";}}await db.SaveChangesAsync(ct);await Hist(e,old,e.Status,u,r.Reason,ct);await Audit(u,"material_request.warehouse_reviewed",e,null,r.Reason,ct);return Map(e);}
 public Task<MaterialRequestResponse?> PrepareAsync(string id,MaterialRequestReasonRequest r,UserAccessContext u,CancellationToken ct)=>Change(id,u,ct,"material_request.prepared",r.Reason,x=>{WarehouseWork(u);Status(x,MaterialRequestStatus.Reservada,MaterialRequestStatus.PendienteStock,MaterialRequestStatus.PendienteAbastecimiento);x.Status=MaterialRequestStatus.EnPreparacion.ToString();});
 public async Task<MaterialRequestResponse?> DeliverAsync(string id,DeliverRequestedMaterialRequest r,UserAccessContext u,CancellationToken ct){WarehouseWork(u);var e=await Find(id,ct);if(e is null)return null;Faena(u,e.Faena?.Code);Status(e,MaterialRequestStatus.Reservada,MaterialRequestStatus.EnPreparacion);var i=e.Items.Single();if(Parse(e.RequestType,MaterialRequestType.RepuestoCodificado)==MaterialRequestType.RepuestoCodificado){var m=await inventory.DeliverMaterialAsync(new DeliverMaterialRequest(i.SparePart!.Code,r.BodegaCodigo,i.RequestedQuantity,$"Solicitud {e.RequestNumber}: {r.Reason}",e.WorkOrder?.WorkOrderNumber,e.Asset?.Code,e.Faena?.Code,i.Reservation?.ReservationNumber),u,ct);i.DeliveryMovementNumber=m.MovimientoId;i.DeliveredQuantity=i.RequestedQuantity;}var old=e.Status;e.Status=MaterialRequestStatus.Entregada.ToString();await db.SaveChangesAsync(ct);await Hist(e,old,e.Status,u,r.Reason,ct);await Audit(u,"material_request.delivered",e,null,r.Reason,ct);return Map(e);}
 public Task<MaterialRequestResponse?> ReceiveAsync(string id,MaterialRequestReasonRequest r,UserAccessContext u,CancellationToken ct)=>Change(id,u,ct,"material_request.received",r.Reason,x=>{Request(u);Status(x,MaterialRequestStatus.Entregada);x.Status=MaterialRequestStatus.RecibidaPorTecnico.ToString();x.ReceivedByUserId=u.UserId;x.ReceivedAtUtc=DateTimeOffset.UtcNow;});
 public Task<MaterialRequestResponse?> CloseAsync(string id,MaterialRequestReasonRequest r,UserAccessContext u,CancellationToken ct)=>Change(id,u,ct,"material_request.closed",r.Reason,x=>{Maint(u);Status(x,MaterialRequestStatus.RecibidaPorTecnico);x.Status=MaterialRequestStatus.Cerrada.ToString();x.ClosedAtUtc=DateTimeOffset.UtcNow;});
 public async Task<MaterialRequestResponse?> ConvertToSparePartAsync(string id,ConvertMaterialRequestToSparePartRequest r,UserAccessContext u,CancellationToken ct){WarehouseApprove(u);var e=await Find(id,ct);if(e is null)return null;var i=e.Items.Single();if(Parse(e.RequestType,MaterialRequestType.RepuestoCodificado)!=MaterialRequestType.MaterialNoCodificado||i.SparePartId.HasValue||!e.MaintenanceApprovedAtUtc.HasValue||E(e.WarehouseApproverUserId))throw new DomainException("La conversion a repuesto maestro requiere aprobacion de mantenimiento y revision de bodega.");var p=await inventory.CreateSparePartAsync(new CreateSparePartRequest(r.Descripcion,r.UnidadMedida,r.CodigoSap,r.CodigoProveedor,r.DescripcionTecnica??e.TechnicalDescription,r.FamiliaEquipo,r.MarcaFabricante,r.ModeloReferencia,r.Critico,r.StockMinimo,r.StockMaximo,r.PuntoReposicion,r.LeadTimeEsperadoDias,ProveedorPreferente:r.ProveedorPreferente),u,ct);i.SparePart=await Part(p.Summary.Codigo,ct);i.MasterSparePartCode=p.Summary.Codigo;e.ConvertedByUserId=u.UserId;e.ConvertedAtUtc=DateTimeOffset.UtcNow;e.StockDecision="Convertido a repuesto maestro; pendiente abastecimiento";await db.SaveChangesAsync(ct);return Map(e);}
 private async Task<MaterialRequestResponse?> Change(string id,UserAccessContext u,CancellationToken ct,string action,string reason,Action<MaterialRequestEntity> change){Need(reason,"Reason");var e=await Find(id,ct);if(e is null)return null;Faena(u,e.Faena?.Code);var old=e.Status;change(e);e.Observations=E(e.Observations)?reason:$"{e.Observations} | {reason}";await db.SaveChangesAsync(ct);await Hist(e,old,e.Status,u,reason,ct);await Audit(u,action,e,null,reason,ct);return Map(e);}
 private IQueryable<MaterialRequestEntity> Base()=>db.Set<MaterialRequestEntity>().Include(x=>x.Faena).Include(x=>x.WorkOrder).Include(x=>x.Asset).Include(x=>x.Warehouse).Include(x=>x.Items).ThenInclude(x=>x.SparePart).Include(x=>x.Items).ThenInclude(x=>x.Reservation);
 private Task<MaterialRequestEntity?> Find(string id,CancellationToken ct)=>Base().SingleOrDefaultAsync(x=>x.RequestNumber.ToUpper()==id.Trim().ToUpper(),ct);
 private async Task<string> Next(CancellationToken ct){var n=await db.Database.SqlQueryRaw<long>("SELECT nextval('material_request_number_seq') AS \"Value\"").SingleAsync(ct);return $"SOL-{n:000000}";}
 private async Task<FaenaEntity?> FaenaEntity(string? c,CancellationToken ct)=>E(c)?null:await db.Faenas.SingleOrDefaultAsync(x=>x.Code==c!.Trim().ToUpper(),ct); private async Task<WorkOrderEntity?> Ot(string? c,CancellationToken ct)=>E(c)?null:await db.WorkOrders.SingleOrDefaultAsync(x=>x.WorkOrderNumber==c!.Trim().ToUpper(),ct); private async Task<AssetEntity?> Asset(string? c,CancellationToken ct)=>E(c)?null:await db.Assets.SingleOrDefaultAsync(x=>x.Code==c!.Trim().ToUpper(),ct); private async Task<WarehouseEntity?> Warehouse(string c,CancellationToken ct)=>await db.Warehouses.SingleOrDefaultAsync(x=>x.Code==c.Trim().ToUpper(),ct); private async Task<SparePartEntity?> Part(string? c,CancellationToken ct)=>E(c)?null:await db.SpareParts.SingleOrDefaultAsync(x=>x.Code==c!.Trim().ToUpper(),ct);
 private static MaterialRequestResponse Map(MaterialRequestEntity x){var i=x.Items.Single();return new(x.RequestNumber,Parse(x.Status,MaterialRequestStatus.Solicitada),Parse(x.RequestType,MaterialRequestType.RepuestoCodificado),Parse(x.Source,MaterialRequestSource.Bodega),x.RequesterUserId,x.RequestedAtUtc,x.TechnicalDescription,i.RequestedQuantity,x.Unit,x.Reason,i.SparePart?.Code,i.MasterSparePartCode,x.PhotoReference,x.Asset?.Code,x.WorkOrder?.WorkOrderNumber,x.TaskCode,x.Faena?.Code,x.Warehouse?.Code,i.Reservation?.ReservationNumber,i.DeliveryMovementNumber,x.StockDecision,x.MaintenanceApproverUserId,x.MaintenanceApprovedAtUtc,x.WarehouseApproverUserId,x.WarehouseApprovedAtUtc,x.RejectedByUserId,x.RejectedAtUtc,x.RejectReason,x.ReceivedByUserId,x.ReceivedAtUtc,x.ConvertedByUserId,x.ConvertedAtUtc,x.ClosedAtUtc,x.Observations);}
 private async Task Hist(MaterialRequestEntity e,string old,string next,UserAccessContext u,string reason,CancellationToken ct){db.Add(new MaterialRequestStatusHistoryEntity{MaterialRequestId=e.Id,PreviousStatus=old,NewStatus=next,UserId=u.UserId,Reason=reason});await db.SaveChangesAsync(ct);} private Task Audit(UserAccessContext u,string a,MaterialRequestEntity e,object? p,string? r,CancellationToken ct)=>audit.RecordAsync(new AuditEventRequest(u.UserId,a,AuditModules.MaterialRequests,"MaterialRequest",e.RequestNumber,null,JsonSerializer.Serialize(new{e.RequestNumber,e.Status}),e.Faena?.Code,AuditSeverity.Medium,r),ct);
 private static void Validate(CreateMaterialRequestRequest r){Need(r.DescripcionTecnica,"DescripcionTecnica");Need(r.Unidad,"Unidad");Need(r.Motivo,"Motivo");if(r.Cantidad<=0)throw new DomainException("La cantidad solicitada debe ser mayor a cero.");if(r.Type==MaterialRequestType.RepuestoCodificado)Need(r.RepuestoCodigo,"RepuestoCodigo");if(r.Source is MaterialRequestSource.OT or MaterialRequestSource.Tarea)Need(r.OtNumero,"OtNumero");if(r.Source==MaterialRequestSource.Tarea)Need(r.TareaCodigo,"TareaCodigo");} private static void Status(MaterialRequestEntity e,params MaterialRequestStatus[] s){if(!s.Contains(Parse(e.Status,MaterialRequestStatus.Solicitada)))throw new DomainException($"La solicitud esta en estado {e.Status} y no admite esta accion.");} private static void Need(string? x,string n){if(E(x))throw new DomainException($"El campo {n} es obligatorio.");} private static bool E(string? x)=>string.IsNullOrWhiteSpace(x);private static string? N(string? x)=>E(x)?null:x!.Trim();private static bool Same(string? a,string? b)=>string.Equals(N(a),N(b),StringComparison.OrdinalIgnoreCase);private static T Parse<T>(string? x,T f)where T:struct=>Enum.TryParse<T>(x,true,out var v)?v:f;
 private static bool Role(UserAccessContext u,params string[] r)=>r.Any(x=>u.Roles.Contains(x,StringComparer.OrdinalIgnoreCase));private static bool Access(UserAccessContext u,string? f)=>E(f)||Role(u,AuthRoles.Admin,AuthRoles.Management)||u.Permissions.Contains(AuthPermissions.ViewGlobalWarehouses,StringComparer.OrdinalIgnoreCase)||u.Faenas.Contains(f!,StringComparer.OrdinalIgnoreCase);private static void Faena(UserAccessContext u,string? f){if(!Access(u,f))throw new UnauthorizedAccessException("No tiene acceso a la faena de la solicitud.");}private static void View(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.Planner,AuthRoles.MaintenanceSupervisor,AuthRoles.Technician,AuthRoles.Warehouse,AuthRoles.WarehouseSupervisor,AuthRoles.Management,AuthRoles.FaenaViewer))throw new UnauthorizedAccessException("No tiene permisos para ver solicitudes de repuestos.");}private static void Request(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.Planner,AuthRoles.MaintenanceSupervisor,AuthRoles.Technician,AuthRoles.Warehouse,AuthRoles.WarehouseSupervisor))throw new UnauthorizedAccessException("No tiene permisos para crear o recibir solicitudes.");}private static void Maint(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.Planner,AuthRoles.MaintenanceSupervisor))throw new UnauthorizedAccessException("La aprobacion de mantenimiento requiere supervisor de mantenimiento.");}private static void WarehouseApprove(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.WarehouseSupervisor)&&!u.Permissions.Contains(AuthPermissions.AdjustStock,StringComparer.OrdinalIgnoreCase))throw new UnauthorizedAccessException("La revision de bodega requiere supervisor de bodega.");}private static void WarehouseWork(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.WarehouseSupervisor,AuthRoles.Warehouse)&&!u.Permissions.Contains(AuthPermissions.AdjustStock,StringComparer.OrdinalIgnoreCase))throw new UnauthorizedAccessException("La preparacion y entrega requiere rol de bodega.");}private static void Reject(UserAccessContext u){if(!Role(u,AuthRoles.Admin,AuthRoles.Planner,AuthRoles.MaintenanceSupervisor,AuthRoles.WarehouseSupervisor))throw new UnauthorizedAccessException("No tiene permisos para rechazar solicitudes.");}
}

