using MaintenanceCMMS.Application.Auditing;
using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.Costs;
using MaintenanceCMMS.Domain.Common;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities;
using Microsoft.EntityFrameworkCore;
namespace MaintenanceCMMS.Infrastructure.Costs;
public sealed class CostManagementService(CmmsDbContext db,IAuditService audit):ICostManagementService
{
 public async Task<IReadOnlyCollection<CostResponse>> ListAsync(CostQuery q,UserAccessContext u,CancellationToken ct){View(u);return (await Filter(q).AsNoTracking().Include(x=>x.WorkOrder).Include(x=>x.Asset).Include(x=>x.Faena).ToListAsync(ct)).Select(Map).ToArray();}
 public async Task<CostResponse> CreateAsync(CreateCostRequest r,UserAccessContext u,CancellationToken ct){Manage(u);if(r.Monto<0||string.IsNullOrWhiteSpace(r.Descripcion))throw new DomainException("Monto y descripción son obligatorios.");var wo=await FindOt(r.OtNumero,ct);var asset=await FindAsset(r.ActivoCodigo,ct);var faena=await FindFaena(r.FaenaCodigo,ct)??wo?.Faena??asset?.Faena;if(wo is not null&&asset is not null&&wo.AssetId!=asset.Id)throw new DomainException("El activo no corresponde a la OT.");var part=await FindPart(r.RepuestoCodigo,ct);var movement=await FindMovement(r.MovimientoNumero,ct);decimal amount=r.Monto,unit=r.CostoUnitario??0;if(r.Categoria==CostCategory.ManoObra){var rate=await db.LaborRates.Where(x=>x.IsActive&&(x.Code==r.Especialidad||x.Specialty==r.Especialidad)).OrderByDescending(x=>x.UpdatedAtUtc).FirstOrDefaultAsync(ct)??await db.LaborRates.Where(x=>x.IsActive&&x.Code=="GLOBAL").FirstOrDefaultAsync(ct)??throw new DomainException("No existe tarifa HH vigente.");if(r.Cantidad is null||r.Cantidad<=0)throw new DomainException("Debe indicar HH.");unit=rate.HourlyRate;amount=r.Cantidad.Value*unit;}if(r.Categoria==CostCategory.Repuesto){if(part is null)throw new DomainException("Debe indicar un repuesto existente.");if(r.Cantidad is null||r.Cantidad<=0)throw new DomainException("Debe indicar cantidad.");unit=r.CostoUnitario??part.AverageUnitCost??throw new DomainException("El repuesto no tiene costo histórico.");amount=r.Cantidad.Value*unit;if(movement is not null&&movement.SparePartId!=part.Id)throw new DomainException("El movimiento no corresponde al repuesto.");}var e=new CostEntryEntity{CostNumber=$"CST-{Guid.NewGuid():N}"[..16].ToUpperInvariant(),Category=r.Categoria.ToString(),Amount=amount,Currency=r.Moneda,Description=r.Descripcion.Trim(),OccurredAtUtc=r.Fecha,WorkOrder=wo,Asset=asset??wo?.Asset,Faena=faena,SparePart=part,StockMovement=movement,ContractCode=r.ContratoCodigo?.Trim(),SupplierRut=r.ProveedorRut?.Trim(),Quantity=r.Cantidad,UnitCost=unit==0?null:unit,DocumentUrl=r.DocumentoUrl?.Trim(),CreatedByUserId=u.UserId};db.CostEntries.Add(e);await db.SaveChangesAsync(ct);await Log(u,"cost.created",e,ct);return Map(e);}
 public async Task<CostResponse?> UpdateAsync(string n,UpdateCostRequest r,UserAccessContext u,CancellationToken ct){Manage(u);var e=await db.CostEntries.Include(x=>x.WorkOrder).Include(x=>x.Asset).Include(x=>x.Faena).SingleOrDefaultAsync(x=>x.CostNumber==n,ct);if(e is null)return null;if(r.Monto<0||string.IsNullOrWhiteSpace(r.Descripcion))throw new DomainException("Datos de costo inválidos.");e.Amount=r.Monto;e.Description=r.Descripcion.Trim();e.OccurredAtUtc=r.Fecha;e.DocumentUrl=r.DocumentoUrl?.Trim();e.UpdatedAtUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);await Log(u,"cost.updated",e,ct);return Map(e);}
 public async Task<CostDashboardResponse> DashboardAsync(CostQuery q,UserAccessContext u,CancellationToken ct){var list=await ListAsync(q,u,ct);return new(list.Sum(x=>x.Monto),list.GroupBy(x=>x.Categoria).ToDictionary(x=>x.Key,x=>x.Sum(y=>y.Monto)),list.Where(x=>x.OtNumero is not null).ToArray(),list.Where(x=>x.ActivoCodigo is not null).ToArray(),list.Where(x=>x.ProveedorRut is not null).ToArray(),list.Where(x=>x.ContratoCodigo is not null).ToArray());}
 public async Task<IReadOnlyCollection<CostResponse>> GetWorkOrderCostsAsync(string n,UserAccessContext u,CancellationToken ct)=>await ListAsync(new CostQuery(OtNumero:n),u,ct);
 public async Task<IReadOnlyCollection<UpsertLaborRateRequest>> ListRatesAsync(UserAccessContext u,CancellationToken ct){View(u);return await db.LaborRates.AsNoTracking().OrderBy(x=>x.Code).Select(x=>new UpsertLaborRateRequest(x.Code,x.HourlyRate,x.Specialty,x.IsActive)).ToArrayAsync(ct);}
 public async Task<UpsertLaborRateRequest> UpsertRateAsync(UpsertLaborRateRequest r,UserAccessContext u,CancellationToken ct){Manage(u);if(r.TarifaHora<0||string.IsNullOrWhiteSpace(r.Codigo))throw new DomainException("Tarifa inválida.");var e=await db.LaborRates.SingleOrDefaultAsync(x=>x.Code==r.Codigo.Trim().ToUpper(),ct);if(e is null){e=new LaborRateEntity{Code=r.Codigo.Trim().ToUpper()};db.LaborRates.Add(e);}e.Specialty=r.Especialidad?.Trim();e.HourlyRate=r.TarifaHora;e.IsActive=r.Activa;e.UpdatedAtUtc=DateTimeOffset.UtcNow;await db.SaveChangesAsync(ct);return r with{Codigo=e.Code};}
 public async Task<IReadOnlyCollection<PaymentStatementResponse>> ListPaymentsAsync(UserAccessContext u,CancellationToken ct){View(u);return (await db.PaymentStatements.AsNoTracking().Include(x=>x.Faena).OrderByDescending(x=>x.CreatedAtUtc).ToListAsync(ct)).Select(Map).ToArray();}
 public async Task<PaymentStatementResponse> CreatePaymentAsync(CreatePaymentStatementRequest r,UserAccessContext u,CancellationToken ct){Manage(u);if(r.Monto<=0||string.IsNullOrWhiteSpace(r.NumeroEstadoPago)||string.IsNullOrWhiteSpace(r.ProveedorRut))throw new DomainException("Estado de pago inválido.");if(await db.PaymentStatements.AnyAsync(x=>x.StatementNumber==r.NumeroEstadoPago.Trim(),ct))throw new DomainException("El número de estado de pago ya existe.");var faena=await FindFaena(r.FaenaCodigo,ct);var e=new PaymentStatementEntity{StatementNumber=r.NumeroEstadoPago.Trim(),SupplierRut=r.ProveedorRut.Trim(),Amount=r.Monto,Currency=r.Moneda,ContractCode=r.ContratoCodigo?.Trim(),Faena=faena,DocumentUrl=r.DocumentoUrl?.Trim(),CreatedByUserId=u.UserId};db.PaymentStatements.Add(e);await db.SaveChangesAsync(ct);await audit.RecordAsync(new(u.UserId,"payment.created",AuditModules.Costs,"PaymentStatement",e.StatementNumber,null,null,faena?.Code,AuditSeverity.High,null),ct);return Map(e);}
 public async Task<PaymentStatementResponse?> ChangePaymentStatusAsync(string n,ChangePaymentStatusRequest r,UserAccessContext u,CancellationToken ct){Manage(u);var e=await db.PaymentStatements.Include(x=>x.Faena).SingleOrDefaultAsync(x=>x.StatementNumber==n,ct);if(e is null)return null;var current=Enum.Parse<PaymentStatus>(e.Status);if(!Allowed(current,r.Estado)||r.Estado==PaymentStatus.Rechazado&&string.IsNullOrWhiteSpace(r.Motivo))throw new DomainException("Transición de pago inválida.");e.Status=r.Estado.ToString();e.UpdatedByUserId=u.UserId;e.StatusChangedAtUtc=DateTimeOffset.UtcNow;e.RejectReason=r.Estado==PaymentStatus.Rechazado?r.Motivo?.Trim():null;await db.SaveChangesAsync(ct);await audit.RecordAsync(new(u.UserId,"payment.status_changed",AuditModules.Costs,"PaymentStatement",e.StatementNumber,current.ToString(),e.Status,e.Faena?.Code,AuditSeverity.High,r.Motivo),ct);return Map(e);}
 private IQueryable<CostEntryEntity> Filter(CostQuery q){var x=db.CostEntries.AsQueryable();if(q.Desde.HasValue)x=x.Where(e=>e.OccurredAtUtc>=q.Desde);if(q.Hasta.HasValue)x=x.Where(e=>e.OccurredAtUtc<=q.Hasta);if(q.Categoria.HasValue)x=x.Where(e=>e.Category==q.Categoria.ToString());if(q.OtNumero is not null)x=x.Where(e=>e.WorkOrder!.WorkOrderNumber==q.OtNumero);if(q.ActivoCodigo is not null)x=x.Where(e=>e.Asset!.Code==q.ActivoCodigo);if(q.FaenaCodigo is not null)x=x.Where(e=>e.Faena!.Code==q.FaenaCodigo);if(q.ContratoCodigo is not null)x=x.Where(e=>e.ContractCode==q.ContratoCodigo);if(q.ProveedorRut is not null)x=x.Where(e=>e.SupplierRut==q.ProveedorRut);return x;}
 private Task<WorkOrderEntity?> FindOt(string? s,CancellationToken ct)=>string.IsNullOrWhiteSpace(s)?Task.FromResult<WorkOrderEntity?>(null):db.WorkOrders.Include(x=>x.Faena).Include(x=>x.Asset).SingleOrDefaultAsync(x=>x.WorkOrderNumber==s.Trim(),ct); private Task<AssetEntity?> FindAsset(string? s,CancellationToken ct)=>string.IsNullOrWhiteSpace(s)?Task.FromResult<AssetEntity?>(null):db.Assets.Include(x=>x.Faena).SingleOrDefaultAsync(x=>x.Code==s.Trim(),ct); private Task<FaenaEntity?> FindFaena(string? s,CancellationToken ct)=>string.IsNullOrWhiteSpace(s)?Task.FromResult<FaenaEntity?>(null):db.Faenas.SingleOrDefaultAsync(x=>x.Code==s.Trim(),ct); private Task<SparePartEntity?> FindPart(string? s,CancellationToken ct)=>string.IsNullOrWhiteSpace(s)?Task.FromResult<SparePartEntity?>(null):db.SpareParts.SingleOrDefaultAsync(x=>x.Code==s.Trim(),ct); private Task<StockMovementEntity?> FindMovement(string? s,CancellationToken ct)=>string.IsNullOrWhiteSpace(s)?Task.FromResult<StockMovementEntity?>(null):db.StockMovements.SingleOrDefaultAsync(x=>x.MovementNumber==s.Trim(),ct);
 private static CostResponse Map(CostEntryEntity e)=>new(e.CostNumber,Enum.Parse<CostCategory>(e.Category),e.Amount,e.Currency,e.Description,e.OccurredAtUtc,e.WorkOrder?.WorkOrderNumber,e.Asset?.Code,e.Faena?.Code,e.ContractCode,e.SupplierRut,e.Quantity,e.UnitCost,e.DocumentUrl,e.CreatedByUserId);private static PaymentStatementResponse Map(PaymentStatementEntity e)=>new(e.StatementNumber,e.SupplierRut,e.Amount,e.Currency,Enum.Parse<PaymentStatus>(e.Status),e.ContractCode,e.Faena?.Code,e.DocumentUrl,e.CreatedAtUtc,e.UpdatedByUserId,e.StatusChangedAtUtc,e.RejectReason);private static bool Allowed(PaymentStatus a,PaymentStatus b)=>a switch{PaymentStatus.Pendiente=>b is PaymentStatus.Enviado or PaymentStatus.Rechazado,PaymentStatus.Enviado=>b is PaymentStatus.Aprobado or PaymentStatus.Rechazado,PaymentStatus.Aprobado=>b==PaymentStatus.Pagado,_=>false};private static void View(UserAccessContext u){if(!u.Roles.Contains(AuthRoles.Admin)&&!u.Roles.Contains(AuthRoles.Management)&&!u.Permissions.Contains(AuthPermissions.ViewCosts))throw new UnauthorizedAccessException("No tiene permiso para ver costos.");}private static void Manage(UserAccessContext u){View(u);if(!u.Roles.Contains(AuthRoles.Admin)&&!u.Roles.Contains(AuthRoles.Management)&&!u.Roles.Contains(AuthRoles.Planner)&&!u.Roles.Contains(AuthRoles.MaintenanceSupervisor))throw new UnauthorizedAccessException("No tiene permiso para gestionar costos.");}private Task Log(UserAccessContext u,string a,CostEntryEntity e,CancellationToken ct)=>audit.RecordAsync(new(u.UserId,a,AuditModules.Costs,"CostEntry",e.CostNumber,null,null,e.Faena?.Code,AuditSeverity.Medium,null),ct);
}