using System.Security.Cryptography;
using System.Text;
using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.WorkOrders;
using MaintenanceCMMS.Domain.Common;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities;
using Microsoft.EntityFrameworkCore;

namespace MaintenanceCMMS.Infrastructure.WorkOrders;

public sealed partial class WorkOrderService
{
    public async Task<WorkOrderSupervisorResponse?> AssignSupervisorAsync(string n, AssignWorkOrderSupervisorRequest r, UserAccessContext u, CancellationToken ct)
    {
        Require(u, AuthPermissions.AssignWorkOrderSupervisor, AuthRoles.Planner); var o=await MutOrder(n,u,ct); EnsureOpen(o); var s=await EligibleAsync(r.SupervisorUsuarioId,AuthRoles.MaintenanceSupervisor,o.Faena.Code,ct); var actor=Actor(u); var old=o.SupervisorUserId;
        o.SupervisorUserId=s.Id;o.SupervisorNameSnapshot=s.DisplayName;o.SupervisorAssignedAtUtc=DateTimeOffset.UtcNow;o.SupervisorAssignedByUserId=actor;o.SupervisorReassignmentReason=N(r.MotivoReasignacion);Invalidate(o,actor,"Cambio de supervisor");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.supervisor_assigned",n,old?.ToString(),s.Id.ToString(),o.Faena.Code,r.MotivoReasignacion,ct);return new(o.SupervisorUserId,o.SupervisorNameSnapshot,o.SupervisorAssignedAtUtc);
    }
    public async Task<WorkOrderDetailResponse?> SendToSupervisorAsync(string n, WorkOrderActionRequest r, UserAccessContext u, CancellationToken ct)
    {
        Require(u,AuthPermissions.SendWorkOrderToSupervisor,AuthRoles.Planner);var o=await MutOrder(n,u,ct);EnsureOpen(o);if(!o.SupervisorUserId.HasValue)throw new DomainException("La OT requiere supervisor asignado.");await SetOrderStatusAsync(o,WorkOrderLifecycleStatus.EnviadaSupervisor,u,string.IsNullOrWhiteSpace(r.Reason)?"Enviada al supervisor":r.Reason,ct);await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.sent_to_supervisor",n,null,"EnviadaSupervisor",o.Faena.Code,r.Reason,ct);return await GetByIdAsync(n,u,ct);
    }
    public async Task<IReadOnlyCollection<WorkOrderSummaryResponse>> ListSupervisorAssignedAsync(UserAccessContext u,CancellationToken ct)
    { var id=Actor(u);var query=BaseQuery().AsNoTracking();if(!AnyRole(u,AuthRoles.Admin))query=query.Where(x=>x.SupervisorUserId==id);return (await query.ToArrayAsync(ct)).Select(x=>ToDetail(x).Summary).ToArray(); }
    public async Task<IReadOnlyCollection<WorkOrderTechnicianResponse>?> ListTechniciansAsync(string n,UserAccessContext u,CancellationToken ct)=> (await GetByIdAsync(n,u,ct))?.Technicians;
    public async Task<IReadOnlyCollection<WorkOrderTechnicianResponse>?> AssignTechniciansAsync(string n,AssignWorkOrderTechniciansRequest r,UserAccessContext u,CancellationToken ct)
    {
        if(r.TecnicoUsuarioIds is null||r.TecnicoUsuarioIds.Count==0)throw new DomainException("Debe indicar técnicos.");var o=await MutOrder(n,u,ct);EnsureManageTechnicians(u,o);EnsureOpen(o);var actor=Actor(u);
        foreach(var id in r.TecnicoUsuarioIds.Distinct()){if(o.Technicians.Any(x=>x.IsActive&&x.TechnicianUserId==id))throw new DomainException("El técnico ya está asignado a la OT.");var t=await EligibleAsync(id,AuthRoles.Technician,o.Faena.Code,ct);_dbContext.WorkOrderTechnicians.Add(new WorkOrderTechnicianEntity{Id=Guid.NewGuid(),WorkOrderId=o.Id,TechnicianUserId=id,TechnicianNameSnapshot=t.DisplayName,AssignedAtUtc=DateTimeOffset.UtcNow,AssignedByUserId=actor,IsActive=true});await Audit(u,"work_order.technician_assigned",n,null,id.ToString(),o.Faena.Code,null,ct);}Invalidate(o,actor,"Cambio de técnicos");await _dbContext.SaveChangesAsync(ct);return o.Technicians.Where(x=>x.IsActive).Select(x=>ToTech(o.WorkOrderNumber,x)).ToArray();
    }
    public async Task<WorkOrderTechnicianResponse?> UnassignTechnicianAsync(string n,Guid id,UnassignWorkOrderTechnicianRequest r,UserAccessContext u,CancellationToken ct)
    {
        ValidateRequired(r.MotivoDesasignacion,nameof(r.MotivoDesasignacion));var o=await MutOrder(n,u,ct);EnsureManageTechnicians(u,o);var a=o.Technicians.SingleOrDefault(x=>x.IsActive&&x.TechnicianUserId==id);if(a is null)return null;if(o.Labor.Any(x=>x.IsActive&&x.TechnicianUserId==id))throw new DomainException("El técnico con HH activas sigue requerido para firma.");var actor=Actor(u);a.IsActive=false;a.UnassignedAtUtc=DateTimeOffset.UtcNow;a.UnassignedByUserId=actor;a.UnassignedReason=r.MotivoDesasignacion.Trim();Invalidate(o,actor,"Desasignación de técnico");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.technician_unassigned",n,id.ToString(),null,o.Faena.Code,r.MotivoDesasignacion,ct);return ToTech(o.WorkOrderNumber,a);
    }
    public async Task<IReadOnlyCollection<MyAssignedWorkOrderResponse>> ListMyAssignedAsync(UserAccessContext u,CancellationToken ct)
    {
        var id=Actor(u);var orders=await BaseQuery().AsNoTracking().Where(x=>x.Technicians.Any(t=>t.TechnicianUserId==id&&t.IsActive)||x.Labor.Any(l=>l.TechnicianUserId==id&&l.IsActive)).ToArrayAsync(ct);return orders.Select(ToDetail).Select(d=>new MyAssignedWorkOrderResponse(d.Summary,d.Tasks.Count(x=>x.Estado==WorkOrderTaskStatus.AprobadaSupervisor),d.Tasks.Count==0?0:Math.Round(100m*d.Tasks.Count(x=>x.Estado==WorkOrderTaskStatus.AprobadaSupervisor)/d.Tasks.Count,2),d.Labor.Where(x=>Same(x.TecnicoUserId,id.ToString())).Sum(x=>x.Horas),d.Signatures.Any(x=>Same(x.UsuarioId,id.ToString())))).ToArray();
    }
    public Task<IReadOnlyCollection<WorkOrderUserLookupResponse>> ListSupervisorsAsync(string? f,UserAccessContext u,CancellationToken ct)=>LookupAsync(AuthRoles.MaintenanceSupervisor,f,u,ct);
    public Task<IReadOnlyCollection<WorkOrderUserLookupResponse>> ListTechnicianLookupsAsync(string? f,UserAccessContext u,CancellationToken ct)=>LookupAsync(AuthRoles.Technician,f,u,ct);
    public async Task<IReadOnlyCollection<WorkOrderTaskResponse>?> ListTasksAsync(string n,UserAccessContext u,CancellationToken ct)=>(await GetByIdAsync(n,u,ct))?.Tasks;
    public async Task<WorkOrderTaskResponse?> UpdateTaskAsync(string n,string c,UpdateWorkOrderTaskRequest r,UserAccessContext u,CancellationToken ct)
    {
        ValidateRequired(r.Titulo,nameof(r.Titulo));ValidateRequired(r.Descripcion,nameof(r.Descripcion));if(r.HorasEstimadas<0)throw new DomainException("HH estimadas inválidas.");var o=await MutOrder(n,u,ct);EnsureSupervisor(u,o);var t=Task(o,c);if(Status(t)==WorkOrderTaskStatus.Cancelada)throw new DomainException("Tarea cancelada.");t.Title=r.Titulo.Trim();t.Description=r.Descripcion.Trim();t.AcceptanceCriteria=N(r.CriterioAceptacion);t.EstimatedHours=r.HorasEstimadas;t.ScheduledStartUtc=r.InicioProgramadoUtc;t.ScheduledEndUtc=r.FinProgramadoUtc;t.Observations=N(r.Observaciones);t.UpdatedByUserId=u.UserId;Invalidate(o,Actor(u),"Edición de tarea");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.task_updated",n,null,t,o.Faena.Code,null,ct);return ToTask(o.WorkOrderNumber,t);
    }
    public async Task<WorkOrderTaskResponse?> StartTaskAsync(string n,string c,WorkOrderTaskActionRequest r,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);EnsureTechnician(u,o);var t=Task(o,c);if(Status(t)is not(WorkOrderTaskStatus.PendienteAsignacion or WorkOrderTaskStatus.Asignada or WorkOrderTaskStatus.Observada))throw new DomainException("Estado de tarea incompatible.");t.ActualStartUtc??=DateTimeOffset.UtcNow;await SetTaskStatusAsync(t,WorkOrderTaskStatus.EnEjecucion,u,r.Motivo,ct);await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.task_started",n,null,t,o.Faena.Code,r.Motivo,ct);return ToTask(o.WorkOrderNumber,t);}
    public async Task<WorkOrderTaskResponse?> CompleteTaskAsync(string n,string c,WorkOrderTaskActionRequest r,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);EnsureTechnician(u,o);var t=Task(o,c);if(Status(t)is not(WorkOrderTaskStatus.EnEjecucion or WorkOrderTaskStatus.Observada))throw new DomainException("La tarea no está en ejecución.");EnsureCompletion(o,t);t.TechnicianCompletedAtUtc=DateTimeOffset.UtcNow;t.CompletedByUserId=Actor(u);await SetTaskStatusAsync(t,WorkOrderTaskStatus.CompletadaTecnico,u,r.Motivo,ct);await SetTaskStatusAsync(t,WorkOrderTaskStatus.EnRevisionSupervisor,u,"En revisión",ct);await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.task_completed",n,null,t,o.Faena.Code,r.Motivo,ct);return ToTask(o.WorkOrderNumber,t);}
    public async Task<WorkOrderTaskResponse?> ObserveTaskAsync(string n,string c,ObserveWorkOrderTaskRequest r,UserAccessContext u,CancellationToken ct)
    {ValidateRequired(r.Motivo,nameof(r.Motivo));var o=await MutOrder(n,u,ct);EnsureSupervisor(u,o);var t=Task(o,c);if(Status(t)!=WorkOrderTaskStatus.EnRevisionSupervisor)throw new DomainException("Solo se observa una tarea en revisión.");t.ObservedAtUtc=DateTimeOffset.UtcNow;t.ObservedByUserId=Actor(u);t.ObservationReason=r.Motivo.Trim();await SetTaskStatusAsync(t,WorkOrderTaskStatus.Observada,u,r.Motivo,ct);Invalidate(o,Actor(u),"Observación de tarea");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.task_observed",n,null,t,o.Faena.Code,r.Motivo,ct);return ToTask(o.WorkOrderNumber,t);}
    public async Task<WorkOrderTaskResponse?> ApproveTaskAsync(string n,string c,WorkOrderTaskActionRequest r,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);EnsureSupervisor(u,o);var t=Task(o,c);if(Status(t)!=WorkOrderTaskStatus.EnRevisionSupervisor)throw new DomainException("Solo se aprueba una tarea en revisión.");EnsureCompletion(o,t);if(o.Labor.Any(x=>x.IsActive&&x.TaskId==t.Id&&!x.SupervisorValidated))throw new DomainException("HH pendientes de revisión.");t.SupervisorApprovedAtUtc=DateTimeOffset.UtcNow;t.ApprovedByUserId=Actor(u);await SetTaskStatusAsync(t,WorkOrderTaskStatus.AprobadaSupervisor,u,r.Motivo,ct);await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.task_approved",n,null,t,o.Faena.Code,r.Motivo,ct);return ToTask(o.WorkOrderNumber,t);}
    public async Task<WorkOrderTaskResponse?> CancelTaskAsync(string n,string c,WorkOrderTaskActionRequest r,UserAccessContext u,CancellationToken ct)
    {ValidateRequired(r.Motivo,nameof(r.Motivo));var o=await MutOrder(n,u,ct);EnsureSupervisor(u,o);var t=Task(o,c);t.CancelledAtUtc=DateTimeOffset.UtcNow;t.CancelledByUserId=Actor(u);t.CancellationReason=r.Motivo!.Trim();await SetTaskStatusAsync(t,WorkOrderTaskStatus.Cancelada,u,r.Motivo,ct);Invalidate(o,Actor(u),"Cancelación de tarea");await _dbContext.SaveChangesAsync(ct);return ToTask(o.WorkOrderNumber,t);}
    public async Task<IReadOnlyCollection<WorkOrderLaborResponse>?> ListTaskLaborAsync(string n,string c,UserAccessContext u,CancellationToken ct)=>(await GetByIdAsync(n,u,ct))?.Labor.Where(x=>Same(x.CodigoTarea,c)).ToArray();
    public async Task<WorkOrderLaborResponse?> RegisterOwnLaborAsync(string n,string c,RegisterOwnLaborRequest r,UserAccessContext u,CancellationToken ct)
    {
        ValidateRequired(r.DescripcionTrabajo,nameof(r.DescripcionTrabajo));var o=await MutOrder(n,u,ct);EnsureTechnician(u,o);var t=Task(o,c);if(Status(t)is WorkOrderTaskStatus.AprobadaSupervisor or WorkOrderTaskStatus.Cancelada)throw new DomainException("La tarea no admite HH.");var id=Actor(u);var(start,end,hours)=Times(r.FechaTrabajo,r.HoraInicio,r.HoraFin,r.Horas);await VerifyLaborAsync(id,r.FechaTrabajo,start,end,hours,null,ct);var e=new WorkOrderLaborEntity{Id=Guid.NewGuid(),WorkOrderId=o.Id,TaskId=t.Id,TechnicianUserId=id,RegisteredByUserId=id,Hours=hours,Description=r.DescripcionTrabajo.Trim(),WorkDateUtc=new DateTimeOffset(r.FechaTrabajo.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero),StartTimeUtc=start,EndTimeUtc=end,Comment=r.TipoHora.Trim()};_dbContext.WorkOrderLabor.Add(e);Invalidate(o,id,"Registro de HH");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.labor_registered",n,null,e,o.Faena.Code,null,ct);return ToLabor(o.WorkOrderNumber,t.TaskCode,e);
    }
    public async Task<WorkOrderLaborResponse?> UpdateOwnLaborAsync(string n,Guid id,UpdateOwnLaborRequest r,UserAccessContext u,CancellationToken ct)
    {ValidateRequired(r.Motivo,nameof(r.Motivo));var o=await MutOrder(n,u,ct);var e=o.Labor.SingleOrDefault(x=>x.Id==id&&x.IsActive);if(e is null)return null;if(e.TechnicianUserId!=Actor(u))throw new UnauthorizedAccessException("Solo puede editar sus HH.");var(start,end,hours)=Times(r.FechaTrabajo,r.HoraInicio,r.HoraFin,r.Horas);await VerifyLaborAsync(Actor(u),r.FechaTrabajo,start,end,hours,id,ct);e.Hours=hours;e.Description=r.DescripcionTrabajo.Trim();e.WorkDateUtc=new DateTimeOffset(r.FechaTrabajo.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);e.StartTimeUtc=start;e.EndTimeUtc=end;e.Comment=r.TipoHora.Trim();e.SupervisorValidated=false;e.ValidatedAtUtc=null;e.ValidatedByUserId=null;Invalidate(o,Actor(u),"Corrección de HH");await _dbContext.SaveChangesAsync(ct);return ToLabor(o.WorkOrderNumber,e.Task.TaskCode,e);}
    public async Task<WorkOrderLaborResponse?> ApproveLaborAsync(string n,Guid id,WorkOrderTaskActionRequest r,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);EnsureSupervisor(u,o);var e=o.Labor.SingleOrDefault(x=>x.Id==id&&x.IsActive);if(e is null)return null;e.SupervisorValidated=true;e.ValidatedByUserId=Actor(u);e.ValidatedAtUtc=DateTimeOffset.UtcNow;await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.labor_approved",n,null,e,o.Faena.Code,r.Motivo,ct);return ToLabor(o.WorkOrderNumber,e.Task.TaskCode,e);}
    public async Task<WorkOrderLaborResponse?> VoidLaborAsync(string n,Guid id,VoidWorkOrderLaborRequest r,UserAccessContext u,CancellationToken ct)
    {ValidateRequired(r.Motivo,nameof(r.Motivo));var o=await MutOrder(n,u,ct);var e=o.Labor.SingleOrDefault(x=>x.Id==id&&x.IsActive);if(e is null)return null;if(e.TechnicianUserId!=Actor(u))EnsureSupervisor(u,o);e.IsActive=false;e.AnnulledAtUtc=DateTimeOffset.UtcNow;e.AnnulledByUserId=Actor(u);e.AnnulReason=r.Motivo.Trim();Invalidate(o,Actor(u),"Anulación de HH");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.labor_voided",n,null,e,o.Faena.Code,r.Motivo,ct);return ToLabor(o.WorkOrderNumber,e.Task.TaskCode,e);}
    public async Task<IReadOnlyCollection<WorkOrderEvidenceResponse>?> ListTaskEvidencesAsync(string n,string c,UserAccessContext u,CancellationToken ct)=>(await GetByIdAsync(n,u,ct))?.Evidences.Where(x=>Same(x.CodigoTarea,c)).ToArray();
    public async Task<WorkOrderEvidenceResponse?> RegisterUploadedEvidenceAsync(string n,string c,UploadWorkOrderEvidenceRequest r,Guid fileId,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);EnsureTechnician(u,o);var t=Task(o,c);var f=await _dbContext.Files.SingleOrDefaultAsync(x=>x.Id==fileId&&!x.IsDeleted,ct)??throw new DomainException("Archivo inexistente.");if(string.IsNullOrWhiteSpace(f.MimeType)||!f.MimeType.StartsWith("image/",StringComparison.OrdinalIgnoreCase))throw new DomainException("La evidencia debe ser imagen.");if(!Enum.TryParse<WorkOrderEvidenceType>(r.Tipo,true,out var type)||type is not(WorkOrderEvidenceType.FotoAntes or WorkOrderEvidenceType.FotoDurante or WorkOrderEvidenceType.FotoDespues or WorkOrderEvidenceType.FotoPrueba))throw new DomainException("Tipo de fotografía inválido.");var e=new WorkOrderEvidenceEntity{Id=Guid.NewGuid(),WorkOrderId=o.Id,TaskId=t.Id,FileId=f.Id,Name=f.FileName,EvidenceTypeId=(await CatalogAsync("WorkOrderEvidenceType",type.ToString(),ct)).Id,IsPhoto=true,IsMandatory=t.RequiresEvidence,CoversMandatoryEvidence=true,StorageProvider=f.Provider,ExternalKey=f.FileKey,ExternalUri=f.LogicalUri,LocalPath=f.LogicalPath,SyncStatus="Synced",Observations=N(r.Descripcion),UploadedByUserId=Actor(u),UploadedAtUtc=DateTimeOffset.UtcNow,CapturedAtUtc=r.FechaCapturaUtc};_dbContext.WorkOrderEvidences.Add(e);Invalidate(o,Actor(u),"Nueva evidencia");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.evidence_uploaded",n,null,e,o.Faena.Code,r.Descripcion,ct);return ToEvidence(o.WorkOrderNumber,t.TaskCode,e);}
    public async Task<WorkOrderEvidenceResponse?> VoidEvidenceAsync(string n,Guid id,VoidWorkOrderEvidenceRequest r,UserAccessContext u,CancellationToken ct)
    {ValidateRequired(r.Motivo,nameof(r.Motivo));var o=await MutOrder(n,u,ct);var e=o.Evidences.SingleOrDefault(x=>x.Id==id&&x.IsActive);if(e is null)return null;if(e.UploadedByUserId!=Actor(u))EnsureSupervisor(u,o);e.IsActive=false;e.AnnulledAtUtc=DateTimeOffset.UtcNow;e.AnnulledByUserId=Actor(u);e.AnnulReason=r.Motivo.Trim();Invalidate(o,Actor(u),"Anulación de evidencia");await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.evidence_voided",n,null,e,o.Faena.Code,r.Motivo,ct);return ToEvidence(o.WorkOrderNumber,e.Task.TaskCode,e);}
    public async Task<IReadOnlyCollection<WorkOrderSignatureResponse>?> ListSignaturesAsync(string n,UserAccessContext u,CancellationToken ct)=>(await GetByIdAsync(n,u,ct))?.Signatures;
    public async Task<WorkOrderSignatureResponse?> RegisterOwnSignatureAsync(string n,RegisterOwnWorkOrderSignatureRequest r,Guid fileId,UserAccessContext u,CancellationToken ct)
    {var o=await MutOrder(n,u,ct);var id=Actor(u);EnsureParticipant(u,o,id);var f=await _dbContext.Files.SingleOrDefaultAsync(x=>x.Id==fileId&&!x.IsDeleted,ct)??throw new DomainException("Archivo inexistente.");if(string.IsNullOrWhiteSpace(f.MimeType)||!f.MimeType.StartsWith("image/",StringComparison.OrdinalIgnoreCase))throw new DomainException("La firma debe ser imagen.");if(o.Signatures.Any(x=>x.IsActive&&x.SignerUserId==id))throw new DomainException("Ya existe firma vigente.");if(!o.Labor.Any(x=>x.IsActive&&x.TechnicianUserId==id))throw new DomainException("Debe registrar HH antes de firmar.");if(o.Tasks.Where(ActiveTask).Any(x=>Status(x)is WorkOrderTaskStatus.PendienteAsignacion or WorkOrderTaskStatus.Asignada or WorkOrderTaskStatus.EnEjecucion or WorkOrderTaskStatus.Observada))throw new DomainException("Existen tareas sin completar.");if(o.Tasks.Where(ActiveTask).Any(x=>!o.Evidences.Any(e=>e.IsActive&&e.TaskId==x.Id&&e.IsPhoto)))throw new DomainException("Faltan fotografías.");if(o.Checklist.Any(x=>x.IsActive&&x.Mandatory&&!x.Completed))throw new DomainException("Faltan respuestas preventivas.");var s=new WorkOrderSignatureEntity{Id=Guid.NewGuid(),WorkOrderId=o.Id,SignerUserId=id,FileId=f.Id,SignedAtUtc=DateTimeOffset.UtcNow,Comment=N(r.Comentario),ContentVersion=1,ContentHash=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{o.Id}:{id}:{f.FileKey}"))),IsActive=true};_dbContext.WorkOrderSignatures.Add(s);await _dbContext.SaveChangesAsync(ct);await Audit(u,"work_order.signature_registered",n,null,s,o.Faena.Code,r.Comentario,ct);return ToSignature(o.WorkOrderNumber,s);}
    private async Task<IReadOnlyCollection<WorkOrderUserLookupResponse>> LookupAsync(string role,string? faena,UserAccessContext u,CancellationToken ct)
    {EnsureCanView(u);if(!string.IsNullOrWhiteSpace(faena))EnsureFaena(u,faena);var users=await _dbContext.Users.AsNoTracking().Include(x=>x.Roles).ThenInclude(x=>x.Role).Include(x=>x.Faenas).ThenInclude(x=>x.Faena).Where(x=>x.IsActive&&!x.IsLocked).ToArrayAsync(ct);return users.Where(x=>HasRole(x,role)&&(string.IsNullOrWhiteSpace(faena)||HasRole(x,AuthRoles.Admin)||x.Faenas.Any(f=>f.IsActive&&Same(f.Faena.Code,faena)))).Select(x=>new WorkOrderUserLookupResponse(x.Id,x.Username,x.DisplayName,x.Email)).ToArray();}
    private async Task<AppUserEntity> EligibleAsync(Guid id,string role,string faena,CancellationToken ct)
    {var x=await _dbContext.Users.Include(x=>x.Roles).ThenInclude(x=>x.Role).Include(x=>x.Faenas).ThenInclude(x=>x.Faena).SingleOrDefaultAsync(x=>x.Id==id&&x.IsActive&&!x.IsLocked,ct)??throw new DomainException("Usuario inexistente, inactivo o bloqueado.");if(!HasRole(x,role))throw new DomainException("Rol de usuario inválido.");if(!HasRole(x,AuthRoles.Admin)&&!x.Faenas.Any(f=>f.IsActive&&Same(f.Faena.Code,faena)))throw new DomainException("Usuario sin acceso a faena.");return x;}
    private async Task SetOrderStatusAsync(WorkOrderEntity o,WorkOrderLifecycleStatus next,UserAccessContext u,string reason,CancellationToken ct){var p=o.Status;var n=await CatalogAsync("WorkOrderLifecycleStatus",next.ToString(),ct);o.Status=n;o.StatusId=n.Id;o.UpdatedByUserId=u.UserId;o.UpdatedByUserAtUtc=DateTimeOffset.UtcNow;AddHistory(o,p,n,u,reason,DateTimeOffset.UtcNow);}
    private async Task SetTaskStatusAsync(WorkOrderTaskEntity t,WorkOrderTaskStatus next,UserAccessContext u,string? reason,CancellationToken ct){var p=t.Status;var n=await CatalogAsync("WorkOrderTaskStatus",next.ToString(),ct);t.Status=n;t.StatusId=n.Id;t.UpdatedByUserId=u.UserId;t.UpdatedAtUtc=DateTimeOffset.UtcNow;_dbContext.WorkOrderTaskStatusHistory.Add(new WorkOrderTaskStatusHistoryEntity{Id=Guid.NewGuid(),TaskId=t.Id,PreviousStatusId=p.Id,NewStatusId=n.Id,UserId=Actor(u),OccurredAtUtc=DateTimeOffset.UtcNow,Reason=N(reason)});}
    private async Task VerifyLaborAsync(Guid user,DateOnly date,DateTimeOffset? start,DateTimeOffset? end,decimal hours,Guid? current,CancellationToken ct){var a=new DateTimeOffset(date.ToDateTime(TimeOnly.MinValue),TimeSpan.Zero);var b=a.AddDays(1);var all=await _dbContext.WorkOrderLabor.Where(x=>x.IsActive&&x.TechnicianUserId==user&&x.WorkDateUtc>=a&&x.WorkDateUtc<b&&(!current.HasValue||x.Id!=current.Value)).ToArrayAsync(ct);if(all.Sum(x=>x.Hours)+hours>24)throw new DomainException("Máximo 24 HH por día.");if(start.HasValue&&end.HasValue&&all.Any(x=>x.StartTimeUtc<end&&start<x.EndTimeUtc))throw new DomainException("HH superpuesta.");}
    private static (DateTimeOffset? Start,DateTimeOffset? End,decimal Hours) Times(DateOnly d,TimeOnly? start,TimeOnly? end,decimal? h){if(start.HasValue||end.HasValue){if(!start.HasValue||!end.HasValue)throw new DomainException("Debe indicar inicio y término.");var s=new DateTimeOffset(d.ToDateTime(start.Value),TimeSpan.Zero);var e=new DateTimeOffset(d.ToDateTime(end.Value),TimeSpan.Zero);if(e<=s)throw new DomainException("Término debe ser posterior.");return(s,e,Math.Round((decimal)(e-s).TotalHours,2));}if(!h.HasValue||h<=0)throw new DomainException("HH inválidas.");return(null,null,h.Value);}
    private static void EnsureCompletion(WorkOrderEntity o,WorkOrderTaskEntity t){if(t.RequiresLabor&&!o.Labor.Any(x=>x.IsActive&&x.TaskId==t.Id))throw new DomainException("Falta HH.");if(!o.Evidences.Any(x=>x.IsActive&&x.TaskId==t.Id&&x.IsPhoto))throw new DomainException("Falta fotografía.");if(o.Checklist.Any(x=>x.IsActive&&x.TaskId==t.Id&&x.Mandatory&&!x.Completed))throw new DomainException("Falta checklist.");}
    private void Invalidate(WorkOrderEntity o,Guid by,string reason){foreach(var s in o.Signatures.Where(x=>x.IsActive)){s.IsActive=false;s.InvalidatedByUserId=by;s.InvalidatedAtUtc=DateTimeOffset.UtcNow;s.InvalidationReason=reason;}}
    private static WorkOrderTaskStatus Status(WorkOrderTaskEntity x)=>ParseEnum(x.Status.Code,WorkOrderTaskStatus.PendienteAsignacion);private static bool ActiveTask(WorkOrderTaskEntity x)=>x.IsActive&&Status(x)!=WorkOrderTaskStatus.Cancelada;private static Guid Actor(UserAccessContext x)=>Guid.TryParse(x.UserId,out var id)?id:throw new UnauthorizedAccessException("Usuario sin UUID.");private static bool HasRole(AppUserEntity x,string role)=>x.Roles.Any(r=>r.IsActive&&r.Role.IsActive&&Same(r.Role.Code,role));private static bool Has(UserAccessContext x,string p)=>x.Permissions.Contains(p,StringComparer.OrdinalIgnoreCase);private static void Require(UserAccessContext x,string p,string role){if(AnyRole(x,AuthRoles.Admin)||Has(x,p)||AnyRole(x,role))return;throw new UnauthorizedAccessException("Permiso OT requerido.");}private static void EnsureSupervisor(UserAccessContext x,WorkOrderEntity o){if(AnyRole(x,AuthRoles.Admin))return;var actor=Actor(x);if(o.SupervisorUserId==actor&&(AnyRole(x,AuthRoles.MaintenanceSupervisor)||Has(x,AuthPermissions.ManageWorkOrderTasks)))return;throw new UnauthorizedAccessException("Supervisor responsable requerido.");}private static void EnsureManageTechnicians(UserAccessContext x,WorkOrderEntity o)=>EnsureSupervisor(x,o);private static void EnsureTechnician(UserAccessContext x,WorkOrderEntity o){if(AnyRole(x,AuthRoles.Admin))return;var actor=Actor(x);if(o.Technicians.Any(t=>t.IsActive&&t.TechnicianUserId==actor)&&(AnyRole(x,AuthRoles.Technician)||Has(x,AuthPermissions.ExecuteAssignedWorkOrders)))return;throw new UnauthorizedAccessException("Técnico asignado requerido.");}private static void EnsureParticipant(UserAccessContext x,WorkOrderEntity o,Guid id){if(AnyRole(x,AuthRoles.Admin)||(AnyRole(x,AuthRoles.Technician)&&(o.Technicians.Any(t=>t.IsActive&&t.TechnicianUserId==id)||o.Labor.Any(l=>l.IsActive&&l.TechnicianUserId==id))))return;throw new UnauthorizedAccessException("Participante requerido.");}
}
