using MaintenanceCMMS.Application.Auth;
using MaintenanceCMMS.Application.PreventiveMaintenance;
using MaintenanceCMMS.Application.WorkOrders;
using MaintenanceCMMS.Domain.Common;
using MaintenanceCMMS.Domain.Enums;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql;
using MaintenanceCMMS.Infrastructure.Data.PostgreSql.Entities;
using MaintenanceCMMS.Infrastructure.Assets;
using Microsoft.EntityFrameworkCore;

namespace MaintenanceCMMS.Infrastructure.PreventiveMaintenance;

/// <summary>Preventive plans, scopes, evaluations and history persisted in PostgreSQL tables.</summary>
public sealed class PreventiveMaintenanceService : IPreventiveMaintenanceService
{
    private readonly CmmsDbContext _db;
    public PreventiveMaintenanceService(CmmsDbContext dbContext) => _db = dbContext;

    public async Task<IReadOnlyCollection<PreventivePlanResponse>> ListPlansAsync(PreventivePlanQuery query, UserAccessContext user, CancellationToken ct)
    {
        EnsureView(user); var plans = PlanQuery(); if (!query.IncludeInactive) plans = plans.Where(x => x.IsActive); if (!string.IsNullOrWhiteSpace(query.ActivoCodigo)) plans = plans.Where(x => x.Scopes.Any(s => s.Asset != null && s.Asset.Code == Code(query.ActivoCodigo))); if (!string.IsNullOrWhiteSpace(query.FamiliaEquipo)) plans = plans.Where(x => x.Scopes.Any(s => s.EquipmentFamily != null && s.EquipmentFamily.Code == Code(query.FamiliaEquipo))); if (!string.IsNullOrWhiteSpace(query.FaenaCodigo)) plans = plans.Where(x => x.Scopes.Any(s => (s.Asset != null && s.Asset.Faena != null && s.Asset.Faena.Code == Code(query.FaenaCodigo)) || (s.OperationalUnit != null && s.OperationalUnit.Faena != null && s.OperationalUnit.Faena.Code == Code(query.FaenaCodigo))));
        var all = await plans.OrderBy(x => x.Code).ToListAsync(ct); var response = all.Select(ToPlan).Where(x => x.FaenaCodigo is null || CanAccess(user, x.FaenaCodigo)); return query.Estado is null ? response.ToArray() : response.Where(x => x.Estado == query.Estado).ToArray();
    }

    public async Task<PreventivePlanResponse> UpsertPlanAsync(UpsertPreventivePlanRequest request, UserAccessContext user, CancellationToken ct)
    {
        EnsureManage(user); Required(request.Codigo, nameof(request.Codigo)); Required(request.Nombre, nameof(request.Nombre)); ValidateFrequency(request);
        var asset = await OptionalAsync(_db.Assets, request.ActivoCodigo, x => x.Code, "activo", ct); var family = await OptionalAsync(_db.EquipmentFamilies, request.FamiliaEquipo, x => x.Code, "familia", ct); if (asset is null && family is null) throw new DomainException("El plan debe tener alcance por activo o familia.");
        if (asset is not null) { await _db.Entry(asset).Reference(x => x.OperationalState).LoadAsync(ct); await _db.Entry(asset).Reference(x => x.Faena).LoadAsync(ct); AssetOperationalPolicy.EnsureCanStartOperation(asset, "planes preventivos"); }
        if (asset?.Faena is not null) EnsureAccess(user, asset.Faena.Code);
        var checklist = string.IsNullOrWhiteSpace(request.ChecklistCodigo) ? null : await _db.ChecklistTemplates.SingleOrDefaultAsync(x => x.Code == Code(request.ChecklistCodigo), ct) ?? throw new DomainException($"El checklist '{request.ChecklistCodigo}' no existe.");
        var plan = await PlanQuery().SingleOrDefaultAsync(x => x.Code == Code(request.Codigo), ct);
        if (plan is null) { plan = new PreventivePlanEntity { Code = Code(request.Codigo)!, CreatedByUserId = user.UserId }; _db.PreventivePlans.Add(plan); }
        plan.Name = request.Nombre.Trim(); plan.FrequencyType = Frequency(request); plan.FrequencyHours = request.FrecuenciaHoras; plan.FrequencyKilometers = request.FrecuenciaKm; plan.FrequencyDays = request.FrecuenciaDias; plan.HourTolerance = request.ToleranciaHoras; plan.KilometerTolerance = request.ToleranciaKm; plan.DayTolerance = request.ToleranciaDias; plan.ChecklistTemplateId = checklist?.Id; plan.SuggestedSpareParts = Text(request.RepuestosSugeridos); plan.EstimatedLaborHours = request.HHEstimadas; plan.StartsAtUtc = request.FechaInicio ?? plan.StartsAtUtc ?? DateTimeOffset.UtcNow; plan.NextDueAtUtc = request.FrecuenciaDias is null ? plan.NextDueAtUtc : (request.FechaInicio ?? DateTimeOffset.UtcNow).AddDays(request.FrecuenciaDias.Value); plan.IsActive = request.Activo; plan.UpdatedByUserId = user.UserId; plan.UpdatedAtUtc = DateTimeOffset.UtcNow;
        var scope = plan.Scopes.FirstOrDefault(); if (scope is null) { scope = new PreventivePlanScopeEntity { PreventivePlan = plan }; plan.Scopes.Add(scope); } scope.AssetId = asset?.Id; scope.Asset = asset; scope.EquipmentFamilyId = family?.Id; scope.EquipmentFamily = family; scope.AssetTypeId = asset?.AssetTypeId; scope.AssetType = asset?.AssetTypeDefinition; scope.Brand = Text(request.Marca); scope.Model = Text(request.Modelo);
        await _db.SaveChangesAsync(ct); return ToPlan(plan);
    }

    public async Task<IReadOnlyCollection<PreventiveReadingResponse>> ListReadingsAsync(PreventiveReadingQuery query, UserAccessContext user, CancellationToken ct)
    {
        EnsureView(user); var readings = _db.AssetReadings.AsNoTracking().Include(x => x.Asset).ThenInclude(x => x.Faena).AsQueryable(); if (!string.IsNullOrWhiteSpace(query.ActivoCodigo)) readings = readings.Where(x => x.Asset.Code == Code(query.ActivoCodigo)); if (!string.IsNullOrWhiteSpace(query.FaenaCodigo)) readings = readings.Where(x => x.Asset.Faena != null && x.Asset.Faena.Code == Code(query.FaenaCodigo)); if (query.From is not null) readings = readings.Where(x => x.ReadAtUtc >= query.From); if (query.To is not null) readings = readings.Where(x => x.ReadAtUtc <= query.To); return (await readings.OrderByDescending(x => x.ReadAtUtc).ToListAsync(ct)).Where(x => x.Asset.Faena is not null && CanAccess(user, x.Asset.Faena.Code)).Select(ToReading).ToArray();
    }

    public async Task<PreventiveReadingResponse> RegisterReadingAsync(RegisterPreventiveReadingRequest request, UserAccessContext user, CancellationToken ct)
    {
        EnsureManage(user); Required(request.ActivoCodigo, nameof(request.ActivoCodigo)); if (request.Valor < 0) throw new DomainException("La lectura no puede ser negativa.");
        var asset = await _db.Assets.Include(x => x.Faena).Include(x => x.OperationalState).SingleOrDefaultAsync(x => x.Code == Code(request.ActivoCodigo), ct) ?? throw new DomainException($"El activo '{request.ActivoCodigo}' no existe."); AssetOperationalPolicy.EnsureCanStartOperation(asset, "nuevas lecturas preventivas"); if (asset.Faena is null) throw new DomainException("El activo no tiene faena asignada."); EnsureAccess(user, asset.Faena.Code);
        var last = await _db.AssetReadings.Where(x => x.AssetId == asset.Id).OrderByDescending(x => x.ReadAtUtc).FirstOrDefaultAsync(ct); var correction = last is not null && request.Valor < last.Value; var reading = new AssetReadingEntity { AssetId = asset.Id, Asset = asset, Value = request.Valor, ReadAtUtc = request.FechaLectura, Source = Text(request.Origen)?.ToUpperInvariant() ?? "MANUAL", RegisteredByUserId = user.UserId, EvidenceReference = Text(request.Evidencia), Observations = Text(request.Observaciones), IsCorrection = correction, CorrectedReadingId = correction ? last?.Id : null, IsAnomalous = correction, ValidationMessage = correction ? "La lectura es inferior a la anterior; se registro como correccion." : null }; _db.AssetReadings.Add(reading); await _db.SaveChangesAsync(ct); return ToReading(reading);
    }

    public async Task<PreventiveDashboardResponse> EvaluateAsync(PreventiveEvaluationQuery query, UserAccessContext user, CancellationToken ct)
    {
        EnsureView(user); var evaluatedAt = query.EvaluationDate ?? DateTimeOffset.UtcNow; var plans = await ListPlansAsync(new PreventivePlanQuery(query.FaenaCodigo, query.ActivoCodigo, IncludeInactive: false), user, ct); var due = new List<PreventiveDueResponse>(); var calendar = new List<PreventiveCalendarItemResponse>(); var history = new List<PreventiveHistoryResponse>();
        foreach (var planResponse in plans) { var plan = await PlanQuery().SingleAsync(x => x.Code == planResponse.Codigo, ct); foreach (var asset in await ResolveAssetsAsync(plan, ct)) { var status = await EvaluateStatusAsync(plan, asset, evaluatedAt, ct); var existing = await _db.PreventiveEvaluations.Where(x => x.PreventivePlanId == plan.Id && x.AssetId == asset.Id).OrderByDescending(x => x.EvaluatedAtUtc).FirstOrDefaultAsync(ct); var evaluation = new PreventiveEvaluationEntity { PreventivePlanId = plan.Id, AssetId = asset.Id, Status = (int)status, EvaluatedAtUtc = evaluatedAt, EvaluatedByUserId = user.UserId }; _db.PreventiveEvaluations.Add(evaluation); if (existing is null || existing.Status != (int)status) { var h = new PreventiveHistoryEntity { PreventivePlanId = plan.Id, AssetId = asset.Id, PreviousStatus = existing?.Status ?? (int)PreventiveStatus.Vigente, NewStatus = (int)status, OccurredAtUtc = evaluatedAt, UserId = user.UserId, Reason = "Evaluacion preventiva" }; _db.PreventiveHistory.Add(h); history.Add(ToHistory(h, plan.Code, asset.Code, null)); }
            var reading = await _db.AssetReadings.Where(x => x.AssetId == asset.Id).OrderByDescending(x => x.ReadAtUtc).FirstOrDefaultAsync(ct); var order = await _db.WorkOrders.AsNoTracking().FirstOrDefaultAsync(x => x.PreventivePlanCode == plan.Code && x.AssetId == asset.Id && x.SupervisorClosedAtUtc == null, ct); due.Add(new(plan.Code, plan.Name, asset.Code, asset.Name, asset.Faena?.Code ?? string.Empty, status, plan.NextDueHours is null || reading is null ? null : plan.NextDueHours-reading.Value, plan.NextDueKilometers is null || reading is null ? null : plan.NextDueKilometers-reading.Value, plan.NextDueAtUtc is null ? null : (int)(plan.NextDueAtUtc.Value.Date-evaluatedAt.Date).TotalDays, plan.NextDueAtUtc, order?.WorkOrderNumber, status.ToString())); calendar.Add(new(plan.Code, plan.Name, asset.Code, asset.Name, asset.Faena?.Code ?? string.Empty, plan.NextDueAtUtc ?? evaluatedAt, status, order?.WorkOrderNumber)); }
        }
        await _db.SaveChangesAsync(ct); if (query.GenerateWorkOrders) foreach (var item in due.Where(x => x.Estado is PreventiveStatus.Vencido or PreventiveStatus.EnVentana)) await GenerateWorkOrderAsync(item.PlanCodigo, new(item.ActivoCodigo, "Evaluacion preventiva", false), user, ct); var storedHistory = await _db.PreventiveHistory.AsNoTracking().Include(x => x.PreventivePlan).Include(x => x.Asset).Include(x => x.WorkOrder).OrderByDescending(x => x.OccurredAtUtc).Take(100).ToListAsync(ct); return new(plans, due, calendar, storedHistory.Select(x => ToHistory(x, x.PreventivePlan.Code, x.Asset.Code, x.WorkOrder?.WorkOrderNumber)).ToArray());
    }

    public async Task<PreventiveWorkOrderGenerationResponse> GenerateWorkOrderAsync(string planCode, GeneratePreventiveWorkOrderRequest request, UserAccessContext user, CancellationToken ct)
    {
        EnsureManage(user); var plan = await PlanQuery().SingleOrDefaultAsync(x => x.Code == Code(planCode), ct) ?? throw new DomainException($"El plan '{planCode}' no existe."); var assets = await ResolveAssetsAsync(plan, ct); if (!string.IsNullOrWhiteSpace(request.ActivoCodigo)) assets = assets.Where(x => x.Code == Code(request.ActivoCodigo)).ToList(); var asset = assets.SingleOrDefault() ?? throw new DomainException("El plan no tiene un activo objetivo unico."); if (asset.Faena is null) throw new DomainException("El activo objetivo no tiene faena."); EnsureAccess(user, asset.Faena.Code);
        if (!_db.Entry(asset).Reference(x => x.OperationalState).IsLoaded) await _db.Entry(asset).Reference(x => x.OperationalState).LoadAsync(ct); AssetOperationalPolicy.EnsureCanStartOperation(asset, "ordenes preventivas");
        var existing = await _db.WorkOrders.FirstOrDefaultAsync(x => x.PreventivePlanCode == plan.Code && x.AssetId == asset.Id && x.SupervisorClosedAtUtc == null, ct); if (existing is not null && !request.Force) return new(plan.Code, asset.Code, existing.WorkOrderNumber, PreventiveStatus.OTGenerada, ["Ya existe una OT preventiva abierta."]);
        var status = await _db.WorkCatalogs.SingleAsync(x => x.Category == "WorkOrderLifecycleStatus" && x.Code == WorkOrderLifecycleStatus.OTCreada.ToString(), ct); var maintenanceType = await _db.WorkCatalogs.SingleAsync(x => x.Category == "MaintenanceType" && x.Code == MaintenanceType.Preventive.ToString(), ct); var number = await NextWorkOrderNumberAsync(ct); var order = new WorkOrderEntity { WorkOrderNumber = number, AssetId = asset.Id, FaenaId = asset.FaenaId!.Value, StatusId = status.Id, MaintenanceTypeId = maintenanceType.Id, Description = $"Preventivo {plan.Code}: {plan.Name}", PreventivePlanCode = plan.Code, PreventiveTemplateId = plan.ChecklistTemplateId, PreventiveTemplateVersionSnapshot = plan.ChecklistTemplateId.HasValue ? 1 : null, IsAutomaticPreventive = true, ScheduledAtUtc = plan.NextDueAtUtc, CreatedByUserId = user.UserId, CreatedByUserAtUtc = DateTimeOffset.UtcNow }; _db.WorkOrders.Add(order);
        if (plan.ChecklistTemplateId.HasValue)
        {
            var items = await _db.ChecklistTemplateItems.Include(x => x.ResponseType).Where(x => x.TemplateId == plan.ChecklistTemplateId && x.IsActive).OrderBy(x => x.SortOrder).ToArrayAsync(ct);
            var taskStatus = await _db.WorkCatalogs.SingleAsync(x => x.Category == "WorkOrderTaskStatus" && x.Code == "PendienteAsignacion", ct);
            foreach (var item in items)
            {
                var task = new WorkOrderTaskEntity { Id = Guid.NewGuid(), WorkOrderId = order.Id, TaskCode = $"PP-{item.SortOrder:000}", Title = item.ItemText, Description = item.ItemText, StatusId = taskStatus.Id, Origin = "PautaPreventiva", PreventiveTemplateId = plan.ChecklistTemplateId, PreventiveTemplateItemId = item.Id, PreventiveTemplateVersionSnapshot = 1, IsMandatoryPreventive = item.Mandatory, RequiresEvidence = item.RequiresPhoto, RequiresLabor = true, ChecklistMandatory = item.Mandatory, CreatedByUserId = user.UserId };
                _db.WorkOrderTasks.Add(task);
                _db.WorkOrderChecklist.Add(new WorkOrderChecklistEntity { Id = Guid.NewGuid(), WorkOrderId = order.Id, TaskId = task.Id, TemplateId = plan.ChecklistTemplateId, TemplateItemId = item.Id, ItemText = item.ItemText, Mandatory = item.Mandatory, ResponseTypeId = item.ResponseTypeId, RequiresPhoto = item.RequiresPhoto, RequiresFile = item.RequiresFile, RequiresSignature = item.RequiresSignature });
            }
        }
        var history = new PreventiveHistoryEntity { PreventivePlanId = plan.Id, AssetId = asset.Id, PreviousStatus = (int)await EvaluateStatusAsync(plan, asset, DateTimeOffset.UtcNow, ct), NewStatus = (int)PreventiveStatus.OTGenerada, OccurredAtUtc = DateTimeOffset.UtcNow, UserId = user.UserId, Reason = Text(request.Reason) ?? "OT preventiva generada", WorkOrder = order }; _db.PreventiveHistory.Add(history); await _db.SaveChangesAsync(ct); return new(plan.Code, asset.Code, number, PreventiveStatus.OTGenerada, []);
    }

    public async Task<PreventivePlanResponse?> ReprogramAsync(string planCode, ReprogramPreventivePlanRequest request, UserAccessContext user, CancellationToken ct)
    {
        EnsureManage(user); var plan = await PlanQuery().SingleOrDefaultAsync(x => x.Code == Code(planCode), ct); if (plan is null) return null; plan.NextDueAtUtc = request.ProximaFecha ?? plan.NextDueAtUtc; plan.NextDueHours = request.ProximaHora ?? plan.NextDueHours; plan.NextDueKilometers = request.ProximoKm ?? plan.NextDueKilometers; plan.UpdatedAtUtc = DateTimeOffset.UtcNow; plan.UpdatedByUserId = user.UserId; foreach (var asset in await ResolveAssetsAsync(plan, ct)) _db.PreventiveHistory.Add(new PreventiveHistoryEntity { PreventivePlanId = plan.Id, AssetId = asset.Id, PreviousStatus = (int)PreventiveStatus.EnVentana, NewStatus = (int)PreventiveStatus.Reprogramado, OccurredAtUtc = DateTimeOffset.UtcNow, UserId = user.UserId, Reason = Text(request.Reason) ?? "Plan reprogramado" }); await _db.SaveChangesAsync(ct); return ToPlan(plan);
    }

    public async Task<PreventiveEngineRunResponse> RunAutomaticEvaluationAsync(UserAccessContext user, CancellationToken ct) { var dashboard = await EvaluateAsync(new(GenerateWorkOrders: true), user, ct); return new(dashboard.DueItems.Count, dashboard.DueItems.Count(x => x.NumeroOT is not null), 0, []); }

    private IQueryable<PreventivePlanEntity> PlanQuery() => _db.PreventivePlans.Include(x => x.Scopes).ThenInclude(x => x.Asset).ThenInclude(x => x!.Faena).Include(x => x.Scopes).ThenInclude(x => x.EquipmentFamily).Include(x => x.Scopes).ThenInclude(x => x.OperationalUnit).ThenInclude(x => x!.Faena).Include(x => x.ChecklistTemplate);
    private async Task<List<AssetEntity>> ResolveAssetsAsync(PreventivePlanEntity plan, CancellationToken ct) { var result = new Dictionary<Guid,AssetEntity>(); foreach (var s in plan.Scopes) { if (s.Asset is not null) result[s.Asset.Id] = s.Asset; if (s.EquipmentFamilyId is not null) foreach(var a in await _db.Assets.Include(x=>x.Faena).Where(x=>x.FamilyId == s.EquipmentFamilyId).ToListAsync(ct)) result[a.Id]=a; if(s.AssetTypeId is not null) foreach(var a in await _db.Assets.Include(x=>x.Faena).Where(x=>x.AssetTypeId==s.AssetTypeId).ToListAsync(ct)) result[a.Id]=a; } return result.Values.ToList(); }
    private async Task<PreventiveStatus> EvaluateStatusAsync(PreventivePlanEntity p, AssetEntity a, DateTimeOffset now, CancellationToken ct) { var reading = await _db.AssetReadings.Where(x=>x.AssetId==a.Id).OrderByDescending(x=>x.ReadAtUtc).FirstOrDefaultAsync(ct); if(p.NextDueAtUtc is not null){var days=(p.NextDueAtUtc.Value.Date-now.Date).TotalDays; if(days< -p.DayTolerance)return PreventiveStatus.Vencido; if(days<=p.DayTolerance)return PreventiveStatus.EnVentana; if(days<=p.DayTolerance+7)return PreventiveStatus.ProximoAVencer;} if(reading is not null && p.NextDueHours is not null){var remaining=p.NextDueHours-reading.Value; if(remaining < -p.HourTolerance)return PreventiveStatus.Vencido; if(remaining<=p.HourTolerance)return PreventiveStatus.EnVentana;} return PreventiveStatus.Vigente; }
    private static int Frequency(UpsertPreventivePlanRequest r) => r.FrecuenciaDias is not null && r.FrecuenciaHoras is null && r.FrecuenciaKm is null ? (int)PreventiveFrequencyType.Calendario : r.FrecuenciaHoras is not null && r.FrecuenciaKm is null && r.FrecuenciaDias is null ? (int)PreventiveFrequencyType.Horas : r.FrecuenciaKm is not null && r.FrecuenciaHoras is null && r.FrecuenciaDias is null ? (int)PreventiveFrequencyType.Kilometros : (int)PreventiveFrequencyType.Mixta;
    private static void ValidateFrequency(UpsertPreventivePlanRequest r){ if(r.HHEstimadas<=0)throw new DomainException("Las HH estimadas deben ser mayores a cero."); if(r.FrecuenciaHoras is null && r.FrecuenciaKm is null && r.FrecuenciaDias is null)throw new DomainException("Debe indicar al menos una frecuencia."); if(r.FrecuenciaHoras<=0 || r.FrecuenciaKm<=0 || r.FrecuenciaDias<=0)throw new DomainException("Las frecuencias deben ser positivas."); }
    private static PreventivePlanResponse ToPlan(PreventivePlanEntity p){var s=p.Scopes.FirstOrDefault();var asset=s?.Asset;var status=p.NextDueAtUtc is not null && p.NextDueAtUtc<DateTimeOffset.UtcNow ? PreventiveStatus.Vencido:PreventiveStatus.Vigente;return new(p.Code,p.Name,asset?.Code,asset?.Name,asset?.Faena?.Code,s?.EquipmentFamily?.Code,s?.Brand,s?.Model,(PreventiveFrequencyType)p.FrequencyType,p.FrequencyHours,p.FrequencyKilometers,p.FrequencyDays,p.HourTolerance,p.KilometerTolerance,p.DayTolerance,p.ChecklistTemplate?.Code,p.SuggestedSpareParts,p.EstimatedLaborHours,p.StartsAtUtc,p.LastExecutedAtUtc,p.LastExecutedHours,p.LastExecutedKilometers,p.NextDueAtUtc,p.NextDueHours,p.NextDueKilometers,status,p.IsActive);}
    private static PreventiveReadingResponse ToReading(AssetReadingEntity x)=>new(x.Id.ToString("N"),x.Asset.Code,x.Asset.Name,x.Asset.Faena?.Code??string.Empty,x.Value,x.Asset.UsageMeasurementType??"UN",x.ReadAtUtc,x.RegisteredByUserId??string.Empty,x.EvidenceReference,x.IsCorrection,x.IsAnomalous,x.ValidationMessage,x.AuthorizedByUserId);
    private static PreventiveHistoryResponse ToHistory(PreventiveHistoryEntity x,string plan,string asset,string? order)=>new(x.Id.ToString("N"),plan,asset,(PreventiveStatus)x.PreviousStatus,(PreventiveStatus)x.NewStatus,x.OccurredAtUtc,x.UserId,x.Reason,order);
    private async Task<string> NextWorkOrderNumberAsync(CancellationToken ct){var values=await _db.WorkOrders.AsNoTracking().Select(x=>x.WorkOrderNumber).ToListAsync(ct);var n=values.Select(x=>int.TryParse(x.Replace("OT-", "", StringComparison.OrdinalIgnoreCase),out var i)?i:0).DefaultIfEmpty().Max()+1;return $"OT-{n:000000}";}
    private static async Task<T?> OptionalAsync<T>(DbSet<T> set,string? value,System.Linq.Expressions.Expression<Func<T,string>> selector,string label,CancellationToken ct)where T:class{if(string.IsNullOrWhiteSpace(value))return null;var normalized=Code(value);var expression=System.Linq.Expressions.Expression.Lambda<Func<T,bool>>(System.Linq.Expressions.Expression.Equal(selector.Body,System.Linq.Expressions.Expression.Constant(normalized)),selector.Parameters);return await set.SingleOrDefaultAsync(expression,ct)??throw new DomainException($"El {label} '{value}' no existe.");}
    private static string? Text(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim();private static string? Code(string? x)=>string.IsNullOrWhiteSpace(x)?null:x.Trim().ToUpperInvariant();private static void Required(string? x,string n){if(string.IsNullOrWhiteSpace(x))throw new DomainException($"El campo {n} es obligatorio.");}
    private static bool CanAccess(UserAccessContext u,string code)=>u.Roles.Contains(AuthRoles.Admin,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.Management,StringComparer.OrdinalIgnoreCase)||u.Faenas.Contains(code,StringComparer.OrdinalIgnoreCase);private static void EnsureAccess(UserAccessContext u,string c){if(!CanAccess(u,c))throw new UnauthorizedAccessException("No tiene acceso a la faena.");}private static void EnsureView(UserAccessContext u){if(!(u.Roles.Contains(AuthRoles.Admin,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.Planner,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.MaintenanceSupervisor,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.Management,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.FaenaViewer,StringComparer.OrdinalIgnoreCase)))throw new UnauthorizedAccessException("No tiene permisos para ver preventivos.");}private static void EnsureManage(UserAccessContext u){if(!(u.Roles.Contains(AuthRoles.Admin,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.Planner,StringComparer.OrdinalIgnoreCase)||u.Roles.Contains(AuthRoles.MaintenanceSupervisor,StringComparer.OrdinalIgnoreCase)))throw new UnauthorizedAccessException("No tiene permisos para gestionar preventivos.");}
}
