import { useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { Dialog } from "../../../shared/ui/Dialog";
import { apiFetch } from "../../auth/authStore";
import { unitQueryKeys } from "./unitQueryKeys";
import { UnitTransferForm, type UnitTransferValue } from "./UnitTransferForm";
type Component = { activoCodigo: string; activoNombre: string; rolComponenteCodigo: string; faenaCodigo?: string | null; ubicacionTecnicaCodigo?: string | null };
type Unit = { codigo: string; faenaCodigo?: string | null; ubicacionTecnicaCodigo?: string | null; composicion: { completa: boolean; vigentes: Component[] } };
const initial = (): UnitTransferValue => ({ faenaDestinoCodigo: "", fechaEfectivaUtc: new Date().toISOString().slice(0, 16), motivo: "", observaciones: "" });
export function UnitTransferDialog({ open, unit, onClose }: { open: boolean; unit: Unit; onClose: () => void }) { const client = useQueryClient(); const [form, setForm] = useState(initial); const chassis = unit.composicion.vigentes.find(item => item.rolComponenteCodigo.toUpperCase().includes("CHASIS")); const factory = unit.composicion.vigentes.find(item => item.rolComponenteCodigo.toUpperCase().includes("FABRICA")); const anchor = chassis ?? unit.composicion.vigentes[0]; const transfer = useMutation({ mutationFn: () => { if (!anchor) throw new Error("La unidad no tiene componentes para trasladar."); return apiFetch("/api/assets/" + encodeURIComponent(anchor.activoCodigo) + "/transfers", { method: "POST", body: JSON.stringify({ faenaDestinoCodigo: form.faenaDestinoCodigo, fechaEfectivaUtc: new Date(form.fechaEfectivaUtc).toISOString(), motivo: form.motivo.trim(), observaciones: form.observaciones.trim() || null, trasladarUnidadCompleta: true }) }); }, onSuccess: async () => { await unitQueryKeys.invalidateTransfer(client, unit.codigo, unit.composicion.vigentes.map(item => item.activoCodigo)); onClose(); } }); return <Dialog open={open} onClose={onClose} title="Trasladar unidad completa" busy={transfer.isPending} footer={<button className="primary-button" type="button" disabled={!unit.composicion.completa || !anchor || !form.faenaDestinoCodigo || !form.motivo.trim() || transfer.isPending} onClick={() => transfer.mutate()}>{transfer.isPending ? "Trasladando..." : "Confirmar traslado"}</button>}><p className="mb-3 text-sm text-amber-700">El traslado es transaccional: se moveran todos los componentes vigentes y no se permiten resultados parciales.</p><dl className="mb-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-slate-500">Faena actual</dt><dd>{unit.faenaCodigo ?? "Sin faena"}</dd></div><div><dt className="text-slate-500">Ubicacion fisica actual</dt><dd>{unit.ubicacionTecnicaCodigo ?? "Taller o sin ubicacion de faena"}</dd></div><div><dt className="text-slate-500">Chasis afectado</dt><dd>{chassis ? chassis.activoNombre + " (" + chassis.activoCodigo + ")" : "No identificado"}</dd></div><div><dt className="text-slate-500">Fabrica afectada</dt><dd>{factory ? factory.activoNombre + " (" + factory.activoCodigo + ")" : "No identificada"}</dd></div></dl>{!unit.composicion.completa ? <p className="error-banner mb-3">La composicion debe estar completa antes de trasladar la unidad.</p> : null}<UnitTransferForm value={form} onChange={setForm} disabled={transfer.isPending} />{transfer.error ? <p className="error-banner mt-3">{transfer.error instanceof Error ? transfer.error.message : "No fue posible trasladar la unidad."}</p> : null}</Dialog>; }
