import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { apiFetch } from "../auth/authStore";
import { useFaenas } from "../faenas/FaenaSelect";
import { Dialog } from "../../shared/ui/Dialog";
import { AssetActionRow } from "./AssetActionRow";

type Catalog={estadosOperacionales:{codigo:string;nombre:string}[]};
type Workshop={tallerCodigo:string;nombre:string;comuna?:string|null};
const now=()=>new Date().toISOString().slice(0,16);
export function AssetActionsPanel({ code, measurementType, unit, lastReading, locationType, faenaCode }: { code:string;measurementType?:string|null;unit?:string|null;lastReading?:number|null;locationType?:string|null;faenaCode?:string|null }) {
 const client=useQueryClient();const {faenas}=useFaenas(false);const [reading,setReading]=useState(false);const [state,setState]=useState(false);const [movement,setMovement]=useState(false);const [value,setValue]=useState("");const [stateForm,setStateForm]=useState({estadoOperacionalCodigo:"",motivo:""});const [moveForm,setMoveForm]=useState({mode:"transfer",faenaDestinoCodigo:"",tallerCodigo:"",fechaEfectivaUtc:now(),motivo:"",observaciones:"",estadoOperacionalDestinoCodigo:""});
 const catalog=useQuery({queryKey:["asset-catalog"],queryFn:()=>apiFetch<Catalog>("/api/assets/catalog")});const workshops=useQuery({queryKey:["workshops"],enabled:movement&&locationType==="FAENA",queryFn:()=>apiFetch<Workshop[]>("/api/scheduling/workshops")});
 const refresh=()=>Promise.all(["equipment-asset-detail","equipment-asset-location","equipment-asset-location-history","equipment-overview","assets"].map(key=>client.invalidateQueries({queryKey:key==="equipment-overview"||key==="assets"?[key]:[key,code]})));
 const read=useMutation({mutationFn:()=>apiFetch("/api/assets/"+encodeURIComponent(code)+"/readings",{method:"POST",body:JSON.stringify({valor:Number(value),fechaLecturaUtc:new Date().toISOString(),origen:"MANUAL"})}),onSuccess:async()=>{setReading(false);setValue("");await refresh()}});
 const saveState=useMutation({mutationFn:()=>apiFetch("/api/assets/"+encodeURIComponent(code)+"/state-events",{method:"POST",body:JSON.stringify({estadoOperacionalCodigo:stateForm.estadoOperacionalCodigo,motivo:stateForm.motivo})}),onSuccess:async()=>{setState(false);setStateForm({estadoOperacionalCodigo:"",motivo:""});await refresh()}});
 const saveMove=useMutation({mutationFn:()=>{const date=new Date(moveForm.fechaEfectivaUtc).toISOString();if(moveForm.mode==="transfer")return apiFetch("/api/assets/"+encodeURIComponent(code)+"/transfers",{method:"POST",body:JSON.stringify({faenaDestinoCodigo:moveForm.faenaDestinoCodigo,fechaEfectivaUtc:date,motivo:moveForm.motivo,observaciones:moveForm.observaciones||null})});if(moveForm.mode==="workshop")return apiFetch("/api/assets/"+encodeURIComponent(code)+"/physical-location/workshop-entry",{method:"POST",body:JSON.stringify({tallerCodigo:moveForm.tallerCodigo,fechaEfectivaUtc:date,motivo:moveForm.motivo||null,observaciones:moveForm.observaciones||null})});return apiFetch("/api/assets/"+encodeURIComponent(code)+"/physical-location/return-to-site",{method:"POST",body:JSON.stringify({fechaEfectivaUtc:date,estadoOperacionalDestinoCodigo:moveForm.estadoOperacionalDestinoCodigo||null,motivo:moveForm.motivo||null,observaciones:moveForm.observaciones||null})})},onSuccess:async()=>{setMovement(false);await refresh()}});
 const effectiveMode=locationType==="TALLER"?"return":locationType==="FAENA"?"workshop":"transfer";
 const openMovement=()=>{setMoveForm(current=>({...current,mode:effectiveMode}));setMovement(true)};
 return <><article className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-semibold">Acciones del activo</h2><div className="mt-3 grid gap-2"><AssetActionRow title="Registrar lectura" description={measurementType?(lastReading===null||lastReading===undefined?"Sin lectura previa":String(lastReading)+" "+(unit||"")):"Sin tipo de medición"} disabled={!measurementType} onClick={()=>setReading(true)}/><AssetActionRow title="Registrar estado" description="Con antecedente auditable" onClick={()=>setState(true)}/><AssetActionRow title="Trasladar, ingresar o retornar" description={locationType==="TALLER"?"Retorno a faena disponible":locationType==="FAENA"?"Ingreso a taller disponible":"Traslado de faena"} onClick={openMovement}/></div></article>
 <Dialog open={reading} onClose={()=>setReading(false)} title="Registrar lectura" busy={read.isPending} footer={<button className="primary-button" disabled={!value||read.isPending} onClick={()=>read.mutate()} type="button">Registrar lectura</button>}><p className="mb-3 text-sm text-slate-500">{measurementType} · {unit||"NA"}</p><label className="block text-sm font-medium">Nueva lectura<input className="input mt-1" min="0" step="0.01" type="number" value={value} onChange={event=>setValue(event.target.value)}/></label></Dialog>
 <Dialog open={state} onClose={()=>setState(false)} title="Registrar estado" busy={saveState.isPending} footer={<button className="primary-button" disabled={!stateForm.estadoOperacionalCodigo||!stateForm.motivo||saveState.isPending} onClick={()=>saveState.mutate()} type="button">Registrar estado</button>}><label className="block text-sm font-medium">Nuevo estado<select className="input mt-1" value={stateForm.estadoOperacionalCodigo} onChange={event=>setStateForm({...stateForm,estadoOperacionalCodigo:event.target.value})}><option value="">Selecciona</option>{catalog.data?.estadosOperacionales.map(item=><option key={item.codigo} value={item.codigo}>{item.nombre}</option>)}</select></label><label className="mt-3 block text-sm font-medium">Motivo<textarea className="input mt-1 min-h-20" value={stateForm.motivo} onChange={event=>setStateForm({...stateForm,motivo:event.target.value})}/></label></Dialog>
 <Dialog open={movement} onClose={()=>setMovement(false)} title="Movimiento de activo" busy={saveMove.isPending} footer={<button className="primary-button" disabled={!moveForm.motivo||saveMove.isPending||(moveForm.mode==="transfer"&&!moveForm.faenaDestinoCodigo)||(moveForm.mode==="workshop"&&!moveForm.tallerCodigo)} onClick={()=>saveMove.mutate()} type="button">Guardar movimiento</button>}><div className="mb-3 flex gap-2"><button className={"secondary-button "+(moveForm.mode==="transfer"?"ring-2 ring-teal-500":"")} onClick={()=>setMoveForm({...moveForm,mode:"transfer"})} type="button">Trasladar</button>{locationType==="FAENA"?<button className={"secondary-button "+(moveForm.mode==="workshop"?"ring-2 ring-teal-500":"")} onClick={()=>setMoveForm({...moveForm,mode:"workshop"})} type="button">Ingresar a taller</button>:null}{locationType==="TALLER"?<button className={"secondary-button "+(moveForm.mode==="return"?"ring-2 ring-teal-500":"")} onClick={()=>setMoveForm({...moveForm,mode:"return"})} type="button">Retornar a faena</button>:null}</div>{moveForm.mode==="transfer"?<label className="block text-sm font-medium">Faena destino<select className="input mt-1" value={moveForm.faenaDestinoCodigo} onChange={event=>setMoveForm({...moveForm,faenaDestinoCodigo:event.target.value})}><option value="">Selecciona</option>{faenas.filter(f=>f.codigo!==faenaCode).map(f=><option key={f.codigo} value={f.codigo}>{f.nombre}</option>)}</select></label>:null}{moveForm.mode==="workshop"?<label className="block text-sm font-medium">Taller<select className="input mt-1" value={moveForm.tallerCodigo} onChange={event=>setMoveForm({...moveForm,tallerCodigo:event.target.value})}><option value="">Selecciona</option>{workshops.data?.map(w=><option key={w.tallerCodigo} value={w.tallerCodigo}>{w.nombre}</option>)}</select></label>:null}{moveForm.mode==="return"?<label className="block text-sm font-medium">Estado al retorno<select className="input mt-1" value={moveForm.estadoOperacionalDestinoCodigo} onChange={event=>setMoveForm({...moveForm,estadoOperacionalDestinoCodigo:event.target.value})}><option value="">Mantener según regla</option>{catalog.data?.estadosOperacionales.map(item=><option key={item.codigo} value={item.codigo}>{item.nombre}</option>)}</select></label>:null}<label className="mt-3 block text-sm font-medium">Fecha efectiva<input className="input mt-1" type="datetime-local" value={moveForm.fechaEfectivaUtc} onChange={event=>setMoveForm({...moveForm,fechaEfectivaUtc:event.target.value})}/></label><label className="mt-3 block text-sm font-medium">Motivo<textarea className="input mt-1 min-h-20" value={moveForm.motivo} onChange={event=>setMoveForm({...moveForm,motivo:event.target.value})}/></label><label className="mt-3 block text-sm font-medium">Observaciones<input className="input mt-1" value={moveForm.observaciones} onChange={event=>setMoveForm({...moveForm,observaciones:event.target.value})}/></label></Dialog></>;
}